package com.example

val b1VocabularyData = listOf(
    VocabularyWord("Meinung", "Opinion", "MY-noong", listOf(ExampleSentence("Was ist deine Meinung dazu?", "// What is your opinion on that?")), "Type: Noun (f) | Category: Communication | IPA: /ˈmaɪ̯nʊŋ/", "B1"),
    VocabularyWord("Diskutieren", "To discuss", "dis-koo-TSEE-ren", listOf(ExampleSentence("Wir müssen das diskutieren.", "// We need to discuss this.")), "Type: Verb | Category: Communication | IPA: /dɪskuˈtiːʁən/", "B1"),
    VocabularyWord("Vorschlag", "Suggestion", "FOR-shlahk", listOf(ExampleSentence("Hast du einen Vorschlag?", "// Do you have a suggestion?")), "Type: Noun (m) | Category: Communication | IPA: /ˈfoːɐ̯ʃlaːk/", "B1"),
    VocabularyWord("Freude", "Joy / Happiness", "FROY-deh", listOf(ExampleSentence("Das macht mir große Freude.", "// That gives me great joy.")), "Type: Noun (f) | Category: Emotions | IPA: /ˈfʁɔʏ̯də/", "B1"),
    VocabularyWord("Enttäuschung", "Disappointment", "ent-TOY-shoong", listOf(ExampleSentence("Das ist eine große Enttäuschung.", "// That is a big disappointment.")), "Type: Noun (f) | Category: Emotions | IPA: /ɛntˈtɔɪ̯ʃʊŋ/", "B1"),
    VocabularyWord("Sorgen", "Worries / To worry", "ZOR-gen", listOf(ExampleSentence("Mach dir keine Sorgen!", "// Don't worry!")), "Type: Noun (pl)/Verb | Category: Emotions | IPA: /ˈzɔʁɡn̩/", "B1"),
    VocabularyWord("Internet", "Internet", "IN-ter-net", listOf(ExampleSentence("Ich suche im Internet.", "// I am searching the internet.")), "Type: Noun (n) | Category: Technology | IPA: /ˈɪntɐnɛt/", "B1"),
    VocabularyWord("Software", "Software", "SOFT-vair", listOf(ExampleSentence("Die Software muss aktualisiert werden.", "// The software must be updated.")), "Type: Noun (f) | Category: Technology | IPA: /ˈsɔftvɛːɐ̯/", "B1"),
    VocabularyWord("Herunterladen", "To download", "hair-OW-ter-lah-den", listOf(ExampleSentence("Ich lade das Programm herunter.", "// I am downloading the program.")), "Type: Verb | Category: Technology | IPA: /ˈhɛʁaʊ̯ntɐˌlaːdn̩/", "B1"),
    VocabularyWord("Gehalt", "Salary", "geh-HALT", listOf(ExampleSentence("Das Gehalt ist gut.", "// The salary is good.")), "Type: Noun (n) | Category: Work | IPA: /ɡəˈhalt/", "B1"),
    VocabularyWord("Bewerbung", "Application", "beh-V AIR-boong", listOf(ExampleSentence("Ich schicke meine Bewerbung ab.", "// I am sending my application.")), "Type: Noun (f) | Category: Work | IPA: /bəˈvɛʁbʊŋ/", "B1"),
    VocabularyWord("Erfahrung", "Experience", "air-FAH-roong", listOf(ExampleSentence("Er hat viel Erfahrung.", "// He has a lot of experience.")), "Type: Noun (f) | Category: Work | IPA: /ɛɐ̯ˈfaːʁʊŋ/", "B1"),
    VocabularyWord("Abschluss", "Degree / Graduation", "AHP-shloos", listOf(ExampleSentence("Ich habe meinen Abschluss gemacht.", "// I got my degree.")), "Type: Noun (m) | Category: Education | IPA: /ˈapʃluːs/", "B1"),
    VocabularyWord("Note", "Grade", "NOH-teh", listOf(ExampleSentence("Ich habe eine gute Note bekommen.", "// I got a good grade.")), "Type: Noun (f) | Category: Education | IPA: /ˈnoːtə/", "B1"),
    VocabularyWord("Teilnehmen", "To participate", "TYEL-nay-men", listOf(ExampleSentence("Ich möchte an dem Kurs teilnehmen.", "// I would like to participate in the course.")), "Type: Verb | Category: Education | IPA: /ˈtaɪ̯lneːmən/", "B1"),
    VocabularyWord("Versuchen", "To try", "fair-ZOOK-en", listOf(ExampleSentence("Ich werde es versuchen.", "// I will try it.")), "Type: Verb | Category: Verbs | IPA: /fɛɐ̯ˈzuːkən/", "B1"),
    VocabularyWord("Entscheiden", "To decide", "ent-SHY-den", listOf(ExampleSentence("Ich muss mich entscheiden.", "// I have to decide.")), "Type: Verb | Category: Verbs | IPA: /ɛntˈʃaɪ̯dən/", "B1"),
    VocabularyWord("Erklären", "To explain", "air-KLAIR-en", listOf(ExampleSentence("Kannst du das erklären?", "// Can you explain that?")), "Type: Verb | Category: Verbs | IPA: /ɛɐ̯ˈklɛːʁən/", "B1"),
    VocabularyWord("Obwohl", "Although", "OP-vohl", listOf(ExampleSentence("Obwohl es regnet, gehe ich spazieren.", "// Although it's raining, I'm going for a walk.")), "Type: Conjunction | Category: Grammar | IPA: /ˈɔpvoːl/", "B1"),
    VocabularyWord("Trotzdem", "Nevertheless", "TROTS-daym", listOf(ExampleSentence("Es regnet, aber ich gehe trotzdem.", "// It's raining, but I'm going anyway.")), "Type: Adverb | Category: Grammar | IPA: /ˈtʁɔtstdem/", "B1"),
    VocabularyWord("Deshalb", "Therefore", "DES-halp", listOf(ExampleSentence("Ich bin krank, deshalb bleibe ich im Bett.", "// I am sick, therefore I am staying in bed.")), "Type: Adverb | Category: Grammar | IPA: /ˈdɛshalp/", "B1"),
    VocabularyWord("Während", "During / While", "VAY-rend", listOf(ExampleSentence("Während ich esse, lese ich.", "// While I eat, I read.")), "Type: Conjunction | Category: Grammar | IPA: /ˈvɛːʁənt/", "B1"),
    VocabularyWord("Bevor", "Before", "beh-FOHR", listOf(ExampleSentence("Bevor ich gehe, esse ich.", "// Before I go, I eat.")), "Type: Conjunction | Category: Grammar | IPA: /bəˈfoːɐ̯/", "B1"),
    VocabularyWord("Nachdem", "After", "NAKH-dahm", listOf(ExampleSentence("Nachdem ich gegessen habe, gehe ich.", "// After I have eaten, I go.")), "Type: Conjunction | Category: Grammar | IPA: /ˈnaxdɛm/", "B1"),
    VocabularyWord("Ich bin der Meinung, dass wir mehr Sport treiben sollten.", "I am of the opinion that we should do more sport.", "-", emptyList(), "Category: Practice Sentences", "B1"),
    VocabularyWord("Könntest du mir bitte erklären, wie das funktioniert?", "Could you please explain to me how that works?", "-", emptyList(), "Category: Practice Sentences", "B1"),
    VocabularyWord("Obwohl es schwierig war, habe ich die Prüfung bestanden.", "Although it was difficult, I passed the exam.", "-", emptyList(), "Category: Practice Sentences", "B1"),
    VocabularyWord("Ich freue mich darauf, dich bald wiederzusehen.", "I am looking forward to seeing you again soon.", "-", emptyList(), "Category: Practice Sentences", "B1"),
    VocabularyWord("Könnten Sie mir sagen, wo die nächste Bank ist?", "Could you tell me where the nearest bank is?", "-", emptyList(), "Category: Practice Sentences", "B1"),
    VocabularyWord("die Arbeitslosigkeit", "unemployment", "-", emptyList(), "Category: Work", "B1"),
    VocabularyWord("die Wirtschaft", "economy", "-", emptyList(), "Category: Work", "B1"),
    VocabularyWord("die Steuer", "tax", "-", emptyList(), "Category: Work", "B1"),
    VocabularyWord("die Beziehung", "relationship", "-", emptyList(), "Category: Emotions", "B1"),
    VocabularyWord("das Vertrauen", "trust", "-", emptyList(), "Category: Emotions", "B1"),
    VocabularyWord("obwohl", "although", "-", emptyList(), "Category: Connectors", "B1"),
    VocabularyWord("während", "while", "-", emptyList(), "Category: Connectors", "B1"),
    VocabularyWord("sobald", "as soon as", "-", emptyList(), "Category: Connectors", "B1"),
    VocabularyWord("sich freuen über / auf", "to be happy about / look forward to", "-", listOf(ExampleSentence("Ich freue mich auf den Urlaub.", "// I am looking forward to the vacation.")), "Category: Verb Prepositions", "B1"),
    VocabularyWord("warten auf (+ Akk)", "to wait for", "-", listOf(ExampleSentence("Ich warte auf dich.", "// I'm waiting for you.")), "Category: Verb Prepositions", "B1"),
    VocabularyWord("Den Nagel auf den Kopf treffen", "To hit the nail on the head", "dayn NAH-gel owf dayn kopf TRAY-fen", listOf(ExampleSentence("Du triffst den Nagel auf den Kopf.", "// You hit the nail on the head.")), "Type: Idiom | IPA: /deːn ˈnaːɡl̩ aʊ̯f deːn kɔpf ˈtʁeːfn̩/", "B1"),
    VocabularyWord("Jemandem auf die Beine helfen", "To help someone back on their feet", "YAY-mand-em owf dee BYE-neh HEL-fen", listOf(ExampleSentence("Er hat mir auf die Beine geholfen.", "// He helped me get back on my feet.")), "Type: Idiom | IPA: /ˈjɛːmandəm aʊ̯f diː ˈbaɪ̯nə ˈhɛlfn̩/", "B1"),
    VocabularyWord("Verantwortung übernehmen", "to take responsibility", "-", emptyList(), "Category: Collocations", "B1"),
    VocabularyWord("eine Entscheidung treffen", "to make a decision", "-", emptyList(), "Category: Collocations", "B1")
)
