package com.example

val top300VerbsData = listOf(
    VocabularyWord("sein", "to be", "-", emptyList(), "Number: 1 | Strong: true", "VERBS"),
    VocabularyWord("haben", "to have", "-", emptyList(), "Number: 2 | Strong: true", "VERBS"),
    VocabularyWord("werden", "to become", "-", emptyList(), "Number: 3 | Strong: true", "VERBS"),
    VocabularyWord("können", "can", "-", emptyList(), "Number: 4 | Strong: true", "VERBS"),
    VocabularyWord("müssen", "must", "-", emptyList(), "Number: 5 | Strong: true", "VERBS"),
    VocabularyWord("sollen", "should", "-", emptyList(), "Number: 6", "VERBS"),
    VocabularyWord("wollen", "to want", "-", emptyList(), "Number: 7 | Strong: true", "VERBS"),
    VocabularyWord("dürfen", "to be allowed", "-", emptyList(), "Number: 8 | Strong: true", "VERBS"),
    VocabularyWord("mögen", "to like", "-", emptyList(), "Number: 9 | Strong: true", "VERBS"),
    VocabularyWord("machen", "to do / make", "-", emptyList(), "Number: 10", "VERBS"),
    VocabularyWord("gehen", "to go", "-", emptyList(), "Number: 11 | Strong: true", "VERBS"),
    VocabularyWord("kommen", "to come", "-", emptyList(), "Number: 12 | Strong: true", "VERBS"),
    VocabularyWord("geben", "to give", "-", emptyList(), "Number: 13 | Strong: true", "VERBS"),
    VocabularyWord("sagen", "to say", "-", emptyList(), "Number: 14", "VERBS"),
    VocabularyWord("stehen", "to stand", "-", emptyList(), "Number: 15 | Strong: true", "VERBS"),
    VocabularyWord("finden", "to find", "-", emptyList(), "Number: 16 | Strong: true", "VERBS"),
    VocabularyWord("bleiben", "to stay", "-", emptyList(), "Number: 17 | Strong: true", "VERBS"),
    VocabularyWord("liegen", "to lie (be located)", "-", emptyList(), "Number: 18 | Strong: true", "VERBS"),
    VocabularyWord("heißen", "to be called", "-", emptyList(), "Number: 19 | Strong: true", "VERBS"),
    VocabularyWord("denken", "to think", "-", emptyList(), "Number: 20 | Strong: true", "VERBS"),
    VocabularyWord("nehmen", "to take", "-", emptyList(), "Number: 21 | Strong: true", "VERBS"),
    VocabularyWord("tun", "to do", "-", emptyList(), "Number: 22 | Strong: true", "VERBS"),
    VocabularyWord("glauben", "to believe", "-", emptyList(), "Number: 23", "VERBS"),
    VocabularyWord("halten", "to hold / stop", "-", emptyList(), "Number: 24 | Strong: true", "VERBS"),
    VocabularyWord("nennen", "to name", "-", emptyList(), "Number: 25 | Strong: true", "VERBS"),
    VocabularyWord("zeigen", "to show", "-", emptyList(), "Number: 26", "VERBS"),
    VocabularyWord("führen", "to lead", "-", emptyList(), "Number: 27", "VERBS"),
    VocabularyWord("sprechen", "to speak", "-", emptyList(), "Number: 28 | Strong: true", "VERBS"),
    VocabularyWord("bringen", "to bring", "-", emptyList(), "Number: 29 | Strong: true", "VERBS"),
    VocabularyWord("leben", "to live", "-", emptyList(), "Number: 30", "VERBS"),
    VocabularyWord("fahren", "to drive / ride", "-", emptyList(), "Number: 31 | Strong: true", "VERBS"),
    VocabularyWord("lassen", "to let / leave", "-", emptyList(), "Number: 32 | Strong: true", "VERBS"),
    VocabularyWord("folgen", "to follow", "-", emptyList(), "Number: 33", "VERBS"),
    VocabularyWord("lernen", "to learn", "-", emptyList(), "Number: 34", "VERBS"),
    VocabularyWord("fragen", "to ask", "-", emptyList(), "Number: 35", "VERBS"),
    VocabularyWord("antworten", "to answer", "-", emptyList(), "Number: 36", "VERBS"),
    VocabularyWord("essen", "to eat", "-", emptyList(), "Number: 37 | Strong: true", "VERBS"),
    VocabularyWord("trinken", "to drink", "-", emptyList(), "Number: 38 | Strong: true", "VERBS"),
    VocabularyWord("schlafen", "to sleep", "-", emptyList(), "Number: 39 | Strong: true", "VERBS"),
    VocabularyWord("lesen", "to read", "-", emptyList(), "Number: 40 | Strong: true", "VERBS"),
    VocabularyWord("schreiben", "to write", "-", emptyList(), "Number: 41 | Strong: true", "VERBS"),
    VocabularyWord("laufen", "to run / walk", "-", emptyList(), "Number: 42 | Strong: true", "VERBS"),
    VocabularyWord("spielen", "to play", "-", emptyList(), "Number: 43", "VERBS"),
    VocabularyWord("arbeiten", "to work", "-", emptyList(), "Number: 44", "VERBS"),
    VocabularyWord("brauchen", "to need", "-", emptyList(), "Number: 45", "VERBS"),
    VocabularyWord("erzählen", "to tell", "-", emptyList(), "Number: 46", "VERBS"),
    VocabularyWord("versuchen", "to try", "-", emptyList(), "Number: 47", "VERBS"),
    VocabularyWord("setzen", "to set / sit", "-", emptyList(), "Number: 48", "VERBS"),
    VocabularyWord("bestehen", "to exist / pass", "-", emptyList(), "Number: 49 | Strong: true", "VERBS"),
    VocabularyWord("erklären", "to explain", "-", emptyList(), "Number: 50", "VERBS"),
    VocabularyWord("erreichen", "to achieve / reach", "-", emptyList(), "Number: 51", "VERBS"),
    VocabularyWord("schaffen", "to manage / create", "-", emptyList(), "Number: 52", "VERBS"),
    VocabularyWord("entwickeln", "to develop", "-", emptyList(), "Number: 53", "VERBS"),
    VocabularyWord("wünschen", "to wish", "-", emptyList(), "Number: 54", "VERBS"),
    VocabularyWord("suchen", "to search", "-", emptyList(), "Number: 55", "VERBS"),
    VocabularyWord("fehlen", "to be missing", "-", emptyList(), "Number: 56", "VERBS"),
    VocabularyWord("bedeuten", "to mean", "-", emptyList(), "Number: 57", "VERBS"),
    VocabularyWord("vergleichen", "to compare", "-", emptyList(), "Number: 58 | Strong: true", "VERBS"),
    VocabularyWord("verdienen", "to earn / deserve", "-", emptyList(), "Number: 59", "VERBS"),
    VocabularyWord("wählen", "to choose / vote", "-", emptyList(), "Number: 60", "VERBS"),
    VocabularyWord("ändern", "to change", "-", emptyList(), "Number: 61", "VERBS"),
    VocabularyWord("prüfen", "to check", "-", emptyList(), "Number: 62", "VERBS"),
    VocabularyWord("bilden", "to form / educate", "-", emptyList(), "Number: 63", "VERBS"),
    VocabularyWord("betrachten", "to consider", "-", emptyList(), "Number: 64", "VERBS"),
    VocabularyWord("unterstützen", "to support", "-", emptyList(), "Number: 65", "VERBS"),
    VocabularyWord("kennen", "to know (person/place)", "-", emptyList(), "Number: 66 | Strong: true", "VERBS"),
    VocabularyWord("wissen", "to know (fact)", "-", emptyList(), "Number: 67 | Strong: true", "VERBS"),
    VocabularyWord("erinnern", "to remember", "-", emptyList(), "Number: 68", "VERBS"),
    VocabularyWord("vorstellen", "to introduce / imagine", "-", emptyList(), "Number: 69", "VERBS"),
    VocabularyWord("handeln", "to act / deal", "-", emptyList(), "Number: 70", "VERBS"),
    VocabularyWord("sorgen", "to care / worry", "-", emptyList(), "Number: 71", "VERBS"),
    VocabularyWord("fallen", "to fall", "-", emptyList(), "Number: 72 | Strong: true", "VERBS"),
    VocabularyWord("treffen", "to meet / hit", "-", emptyList(), "Number: 73 | Strong: true", "VERBS"),
    VocabularyWord("ziehen", "to pull", "-", emptyList(), "Number: 74 | Strong: true", "VERBS"),
    VocabularyWord("erwarten", "to expect", "-", emptyList(), "Number: 75", "VERBS"),
    VocabularyWord("bestimmen", "to determine", "-", emptyList(), "Number: 76", "VERBS"),
    VocabularyWord("besuchen", "to visit", "-", emptyList(), "Number: 77", "VERBS"),
    VocabularyWord("beginnen", "to begin", "-", emptyList(), "Number: 78 | Strong: true", "VERBS"),
    VocabularyWord("gewinnen", "to win", "-", emptyList(), "Number: 79 | Strong: true", "VERBS"),
    VocabularyWord("verlieren", "to lose", "-", emptyList(), "Number: 80 | Strong: true", "VERBS"),
    VocabularyWord("tragen", "to carry / wear", "-", emptyList(), "Number: 81 | Strong: true", "VERBS"),
    VocabularyWord("kaufen", "to buy", "-", emptyList(), "Number: 82", "VERBS"),
    VocabularyWord("verkaufen", "to sell", "-", emptyList(), "Number: 83", "VERBS"),
    VocabularyWord("bezahlen", "to pay", "-", emptyList(), "Number: 84", "VERBS"),
    VocabularyWord("bestellen", "to order", "-", emptyList(), "Number: 85", "VERBS"),
    VocabularyWord("reservieren", "to reserve", "-", emptyList(), "Number: 86", "VERBS"),
    VocabularyWord("buchen", "to book", "-", emptyList(), "Number: 87", "VERBS"),
    VocabularyWord("reisen", "to travel", "-", emptyList(), "Number: 88", "VERBS"),
    VocabularyWord("fliegen", "to fly", "-", emptyList(), "Number: 89 | Strong: true", "VERBS"),
    VocabularyWord("schwimmen", "to swim", "-", emptyList(), "Number: 90 | Strong: true", "VERBS"),
    VocabularyWord("singen", "to sing", "-", emptyList(), "Number: 91 | Strong: true", "VERBS"),
    VocabularyWord("tanzen", "to dance", "-", emptyList(), "Number: 92", "VERBS"),
    VocabularyWord("kochen", "to cook", "-", emptyList(), "Number: 93", "VERBS"),
    VocabularyWord("backen", "to bake", "-", emptyList(), "Number: 94 | Strong: true", "VERBS"),
    VocabularyWord("putzen", "to clean", "-", emptyList(), "Number: 95", "VERBS"),
    VocabularyWord("waschen", "to wash", "-", emptyList(), "Number: 96 | Strong: true", "VERBS"),
    VocabularyWord("anziehen", "to dress / attract", "-", emptyList(), "Number: 97 | Strong: true", "VERBS"),
    VocabularyWord("ausziehen", "to undress / move out", "-", emptyList(), "Number: 98 | Strong: true", "VERBS"),
    VocabularyWord("umziehen", "to move house", "-", emptyList(), "Number: 99 | Strong: true", "VERBS"),
    VocabularyWord("öffnen", "to open", "-", emptyList(), "Number: 100", "VERBS"),
    VocabularyWord("schließen", "to close", "-", emptyList(), "Number: 101 | Strong: true", "VERBS"),
    VocabularyWord("drücken", "to press", "-", emptyList(), "Number: 102", "VERBS"),
    VocabularyWord("drehen", "to turn", "-", emptyList(), "Number: 103", "VERBS"),
    VocabularyWord("legen", "to lay (horizontal)", "-", emptyList(), "Number: 104", "VERBS"),
    VocabularyWord("stellen", "to put (vertical)", "-", emptyList(), "Number: 105", "VERBS"),
    VocabularyWord("hängen", "to hang", "-", emptyList(), "Number: 106 | Strong: true", "VERBS"),
    VocabularyWord("stecken", "to stick / put", "-", emptyList(), "Number: 107", "VERBS"),
    VocabularyWord("holen", "to fetch", "-", emptyList(), "Number: 108", "VERBS"),
    VocabularyWord("senden", "to send", "-", emptyList(), "Number: 109", "VERBS"),
    VocabularyWord("empfangen", "to receive", "-", emptyList(), "Number: 110 | Strong: true", "VERBS"),
    VocabularyWord("teilen", "to share / divide", "-", emptyList(), "Number: 111", "VERBS"),
    VocabularyWord("nutzen", "to use", "-", emptyList(), "Number: 112", "VERBS"),
    VocabularyWord("benutzen", "to use", "-", emptyList(), "Number: 113", "VERBS"),
    VocabularyWord("verwenden", "to use / apply", "-", emptyList(), "Number: 114", "VERBS"),
    VocabularyWord("funktionieren", "to function", "-", emptyList(), "Number: 115", "VERBS"),
    VocabularyWord("reparieren", "to repair", "-", emptyList(), "Number: 116", "VERBS"),
    VocabularyWord("bauen", "to build", "-", emptyList(), "Number: 117", "VERBS"),
    VocabularyWord("wohnen", "to live / reside", "-", emptyList(), "Number: 118", "VERBS"),
    VocabularyWord("mieten", "to rent", "-", emptyList(), "Number: 119", "VERBS"),
    VocabularyWord("besitzen", "to own", "-", emptyList(), "Number: 120 | Strong: true", "VERBS"),
    VocabularyWord("leihen", "to lend / borrow", "-", emptyList(), "Number: 121 | Strong: true", "VERBS"),
    VocabularyWord("schenken", "to give as a gift", "-", emptyList(), "Number: 122", "VERBS"),
    VocabularyWord("einladen", "to invite", "-", emptyList(), "Number: 123 | Strong: true", "VERBS"),
    VocabularyWord("feiern", "to celebrate", "-", emptyList(), "Number: 124", "VERBS"),
    VocabularyWord("gratulieren", "to congratulate", "-", emptyList(), "Number: 125", "VERBS"),
    VocabularyWord("danken", "to thank", "-", emptyList(), "Number: 126", "VERBS"),
    VocabularyWord("bitten", "to ask / request", "-", emptyList(), "Number: 127 | Strong: true", "VERBS"),
    VocabularyWord("hoffen", "to hope", "-", emptyList(), "Number: 128", "VERBS"),
    VocabularyWord("lachen", "to laugh", "-", emptyList(), "Number: 129", "VERBS"),
    VocabularyWord("weinen", "to cry", "-", emptyList(), "Number: 130", "VERBS"),
    VocabularyWord("lächeln", "to smile", "-", emptyList(), "Number: 131", "VERBS"),
    VocabularyWord("schreien", "to scream", "-", emptyList(), "Number: 132 | Strong: true", "VERBS"),
    VocabularyWord("flüstern", "to whisper", "-", emptyList(), "Number: 133", "VERBS"),
    VocabularyWord("rufen", "to call", "-", emptyList(), "Number: 134 | Strong: true", "VERBS"),
    VocabularyWord("klingeln", "to ring", "-", emptyList(), "Number: 135", "VERBS"),
    VocabularyWord("klopfen", "to knock", "-", emptyList(), "Number: 136", "VERBS"),
    VocabularyWord("warten", "to wait", "-", emptyList(), "Number: 137", "VERBS"),
    VocabularyWord("sich beeilen", "to hurry", "-", emptyList(), "Number: 138", "VERBS"),
    VocabularyWord("sich ausruhen", "to rest", "-", emptyList(), "Number: 139", "VERBS"),
    VocabularyWord("sich setzen", "to sit down", "-", emptyList(), "Number: 140", "VERBS"),
    VocabularyWord("sich legen", "to lie down", "-", emptyList(), "Number: 141", "VERBS"),
    VocabularyWord("sich kümmern um", "to take care of", "-", emptyList(), "Number: 142", "VERBS"),
    VocabularyWord("sich treffen", "to meet", "-", emptyList(), "Number: 143 | Strong: true", "VERBS"),
    VocabularyWord("sich unterhalten", "to converse", "-", emptyList(), "Number: 144 | Strong: true", "VERBS"),
    VocabularyWord("sich interessieren für", "to be interested in", "-", emptyList(), "Number: 145", "VERBS"),
    VocabularyWord("sich freuen über / auf", "to be happy about / look forward to", "-", emptyList(), "Number: 146", "VERBS"),
    VocabularyWord("sich erinnern an", "to remember", "-", emptyList(), "Number: 147", "VERBS"),
    VocabularyWord("sich gewöhnen an", "to get used to", "-", emptyList(), "Number: 148", "VERBS"),
    VocabularyWord("sich beschweren über", "to complain about", "-", emptyList(), "Number: 149", "VERBS"),
    VocabularyWord("sich bewerben um", "to apply for", "-", emptyList(), "Number: 150 | Strong: true", "VERBS"),
    VocabularyWord("sich entscheiden für", "to decide on", "-", emptyList(), "Number: 151 | Strong: true", "VERBS"),
    VocabularyWord("sich verlassen auf", "to rely on", "-", emptyList(), "Number: 152 | Strong: true", "VERBS"),
    VocabularyWord("sich konzentrieren auf", "to concentrate on", "-", emptyList(), "Number: 153", "VERBS"),
    VocabularyWord("sich vorbereiten auf", "to prepare for", "-", emptyList(), "Number: 154", "VERBS"),
    VocabularyWord("sich bedanken bei", "to thank", "-", emptyList(), "Number: 155", "VERBS"),
    VocabularyWord("sich entschuldigen für", "to apologize for", "-", emptyList(), "Number: 156", "VERBS"),
    VocabularyWord("sich trennen von", "to separate from", "-", emptyList(), "Number: 157", "VERBS"),
    VocabularyWord("sich unterscheiden von", "to differ from", "-", emptyList(), "Number: 158 | Strong: true", "VERBS"),
    VocabularyWord("sich wundern über", "to marvel at", "-", emptyList(), "Number: 159", "VERBS"),
    VocabularyWord("sich ärgern über", "to be annoyed about", "-", emptyList(), "Number: 160", "VERBS"),
    VocabularyWord("sich fürchten vor", "to be afraid of", "-", emptyList(), "Number: 161", "VERBS"),
    VocabularyWord("sich schämen für", "to be ashamed of", "-", emptyList(), "Number: 162", "VERBS"),
    VocabularyWord("sich sehnen nach", "to long for", "-", emptyList(), "Number: 163", "VERBS"),
    VocabularyWord("sich verlieben in", "to fall in love with", "-", emptyList(), "Number: 164", "VERBS"),
    VocabularyWord("sich streiten mit", "to argue with", "-", emptyList(), "Number: 165 | Strong: true", "VERBS"),
    VocabularyWord("sich verabschieden von", "to say goodbye to", "-", emptyList(), "Number: 166", "VERBS"),
    VocabularyWord("sich verabreden mit", "to make an appointment with", "-", emptyList(), "Number: 167", "VERBS"),
    VocabularyWord("sich melden bei", "to get in touch with", "-", emptyList(), "Number: 168", "VERBS"),
    VocabularyWord("sich anmelden", "to register", "-", emptyList(), "Number: 169", "VERBS"),
    VocabularyWord("sich abmelden", "to deregister", "-", emptyList(), "Number: 170", "VERBS"),
    VocabularyWord("sich wohlfühlen", "to feel comfortable", "-", emptyList(), "Number: 171", "VERBS"),
    VocabularyWord("sich auskennen", "to know one's way around", "-", emptyList(), "Number: 172 | Strong: true", "VERBS"),
    VocabularyWord("sich Mühe geben", "to make an effort", "-", emptyList(), "Number: 173 | Strong: true", "VERBS"),
    VocabularyWord("sich entspannen", "to relax", "-", emptyList(), "Number: 174", "VERBS"),
    VocabularyWord("sich erkälten", "to catch a cold", "-", emptyList(), "Number: 175", "VERBS"),
    VocabularyWord("sich bewegen", "to move (oneself)", "-", emptyList(), "Number: 176", "VERBS"),
    VocabularyWord("sich verhalten", "to behave", "-", emptyList(), "Number: 177 | Strong: true", "VERBS"),
    VocabularyWord("sich benehmen", "to behave (conduct)", "-", emptyList(), "Number: 178 | Strong: true", "VERBS"),
    VocabularyWord("teilnehmen", "to participate", "-", emptyList(), "Number: 179 | Strong: true", "VERBS"),
    VocabularyWord("zunehmen", "to increase / gain weight", "-", emptyList(), "Number: 180 | Strong: true", "VERBS"),
    VocabularyWord("abnehmen", "to decrease / lose weight", "-", emptyList(), "Number: 181 | Strong: true", "VERBS"),
    VocabularyWord("unternehmen", "to undertake", "-", emptyList(), "Number: 182 | Strong: true", "VERBS"),
    VocabularyWord("übernehmen", "to take over", "-", emptyList(), "Number: 183 | Strong: true", "VERBS"),
    VocabularyWord("festnehmen", "to arrest", "-", emptyList(), "Number: 184 | Strong: true", "VERBS"),
    VocabularyWord("anfangen", "to begin", "-", emptyList(), "Number: 185 | Strong: true", "VERBS"),
    VocabularyWord("aufhören", "to stop", "-", emptyList(), "Number: 186", "VERBS"),
    VocabularyWord("anrufen", "to call (telephone)", "-", emptyList(), "Number: 187 | Strong: true", "VERBS"),
    VocabularyWord("ausgehen", "to go out", "-", emptyList(), "Number: 188 | Strong: true", "VERBS"),
    VocabularyWord("einschlafen", "to fall asleep", "-", emptyList(), "Number: 189 | Strong: true", "VERBS"),
    VocabularyWord("aufwachen", "to wake up", "-", emptyList(), "Number: 190", "VERBS"),
    VocabularyWord("aufstehen", "to get up", "-", emptyList(), "Number: 191 | Strong: true", "VERBS"),
    VocabularyWord("fernsehen", "to watch TV", "-", emptyList(), "Number: 192 | Strong: true", "VERBS"),
    VocabularyWord("einkaufen", "to shop", "-", emptyList(), "Number: 193", "VERBS"),
    VocabularyWord("aufräumen", "to tidy up", "-", emptyList(), "Number: 194", "VERBS"),
    VocabularyWord("wegräumen", "to clear away", "-", emptyList(), "Number: 195", "VERBS"),
    VocabularyWord("hinstellen", "to put down", "-", emptyList(), "Number: 196", "VERBS"),
    VocabularyWord("abholen", "to pick up", "-", emptyList(), "Number: 197", "VERBS"),
    VocabularyWord("vorbeikommen", "to come by", "-", emptyList(), "Number: 198 | Strong: true", "VERBS"),
    VocabularyWord("zurückkommen", "to come back", "-", emptyList(), "Number: 199 | Strong: true", "VERBS"),
    VocabularyWord("ankommen", "to arrive", "-", emptyList(), "Number: 200 | Strong: true", "VERBS"),
    VocabularyWord("abfahren", "to depart", "-", emptyList(), "Number: 201 | Strong: true", "VERBS"),
    VocabularyWord("umsteigen", "to change (transport)", "-", emptyList(), "Number: 202 | Strong: true", "VERBS"),
    VocabularyWord("einsteigen", "to get in/on", "-", emptyList(), "Number: 203 | Strong: true", "VERBS"),
    VocabularyWord("aussteigen", "to get out/off", "-", emptyList(), "Number: 204 | Strong: true", "VERBS"),
    VocabularyWord("weitergehen", "to continue walking", "-", emptyList(), "Number: 205 | Strong: true", "VERBS"),
    VocabularyWord("stehen bleiben", "to stop (standing)", "-", emptyList(), "Number: 206 | Strong: true", "VERBS"),
    VocabularyWord("sitzen bleiben", "to stay seated / repeat a class", "-", emptyList(), "Number: 207 | Strong: true", "VERBS"),
    VocabularyWord("hängen bleiben", "to get stuck", "-", emptyList(), "Number: 208 | Strong: true", "VERBS"),
    VocabularyWord("vergessen", "to forget", "-", emptyList(), "Number: 209 | Strong: true", "VERBS"),
    VocabularyWord("behalten", "to keep", "-", emptyList(), "Number: 210 | Strong: true", "VERBS"),
    VocabularyWord("erhalten", "to receive / preserve", "-", emptyList(), "Number: 211 | Strong: true", "VERBS"),
    VocabularyWord("bekommen", "to get", "-", emptyList(), "Number: 212 | Strong: true", "VERBS"),
    VocabularyWord("mitbringen", "to bring along", "-", emptyList(), "Number: 213 | Strong: true", "VERBS"),
    VocabularyWord("mitnehmen", "to take along", "-", emptyList(), "Number: 214 | Strong: true", "VERBS"),
    VocabularyWord("mitmachen", "to join in", "-", emptyList(), "Number: 215", "VERBS"),
    VocabularyWord("nachdenken", "to think about / reflect", "-", emptyList(), "Number: 216 | Strong: true", "VERBS"),
    VocabularyWord("nachfragen", "to inquire", "-", emptyList(), "Number: 217", "VERBS"),
    VocabularyWord("nachschlagen", "to look up", "-", emptyList(), "Number: 218 | Strong: true", "VERBS"),
    VocabularyWord("vorschlagen", "to suggest", "-", emptyList(), "Number: 219 | Strong: true", "VERBS"),
    VocabularyWord("vorbereiten", "to prepare", "-", emptyList(), "Number: 220", "VERBS"),
    VocabularyWord("vorlesen", "to read aloud", "-", emptyList(), "Number: 221 | Strong: true", "VERBS"),
    VocabularyWord("vorhaben", "to plan / intend", "-", emptyList(), "Number: 222 | Strong: true", "VERBS"),
    VocabularyWord("bevorzugen", "to prefer", "-", emptyList(), "Number: 223", "VERBS"),
    VocabularyWord("erlauben", "to permit", "-", emptyList(), "Number: 224", "VERBS"),
    VocabularyWord("verbieten", "to forbid", "-", emptyList(), "Number: 225 | Strong: true", "VERBS"),
    VocabularyWord("empfehlen", "to recommend", "-", emptyList(), "Number: 226 | Strong: true", "VERBS"),
    VocabularyWord("widersprechen", "to contradict", "-", emptyList(), "Number: 227 | Strong: true", "VERBS"),
    VocabularyWord("zustimmen", "to agree", "-", emptyList(), "Number: 228", "VERBS"),
    VocabularyWord("ablehnen", "to reject", "-", emptyList(), "Number: 229", "VERBS"),
    VocabularyWord("akzeptieren", "to accept", "-", emptyList(), "Number: 230", "VERBS"),
    VocabularyWord("verweigern", "to refuse", "-", emptyList(), "Number: 231", "VERBS"),
    VocabularyWord("bitten um", "to ask for", "-", emptyList(), "Number: 232 | Strong: true", "VERBS"),
    VocabularyWord("verlangen", "to demand", "-", emptyList(), "Number: 233", "VERBS"),
    VocabularyWord("erfordern", "to require", "-", emptyList(), "Number: 234", "VERBS"),
    VocabularyWord("sich lohnen", "to be worth it", "-", emptyList(), "Number: 235", "VERBS"),
    VocabularyWord("kosten", "to cost", "-", emptyList(), "Number: 236", "VERBS"),
    VocabularyWord("ausgeben", "to spend", "-", emptyList(), "Number: 237 | Strong: true", "VERBS"),
    VocabularyWord("sparen", "to save", "-", emptyList(), "Number: 238", "VERBS"),
    VocabularyWord("überweisen", "to transfer (money)", "-", emptyList(), "Number: 239 | Strong: true", "VERBS"),
    VocabularyWord("einzahlen", "to deposit", "-", emptyList(), "Number: 240", "VERBS"),
    VocabularyWord("abheben", "to withdraw", "-", emptyList(), "Number: 241 | Strong: true", "VERBS"),
    VocabularyWord("wechseln", "to change / exchange", "-", emptyList(), "Number: 242", "VERBS"),
    VocabularyWord("unterschreiben", "to sign", "-", emptyList(), "Number: 243 | Strong: true", "VERBS"),
    VocabularyWord("ausfüllen", "to fill in", "-", emptyList(), "Number: 244", "VERBS"),
    VocabularyWord("ankreuzen", "to tick", "-", emptyList(), "Number: 245", "VERBS"),
    VocabularyWord("löschen", "to delete / extinguish", "-", emptyList(), "Number: 246", "VERBS"),
    VocabularyWord("speichern", "to save (data)", "-", emptyList(), "Number: 247", "VERBS"),
    VocabularyWord("drucken", "to print", "-", emptyList(), "Number: 248", "VERBS"),
    VocabularyWord("kopieren", "to copy", "-", emptyList(), "Number: 249", "VERBS"),
    VocabularyWord("einscannen", "to scan", "-", emptyList(), "Number: 250", "VERBS"),
    VocabularyWord("herunterladen", "to download", "-", emptyList(), "Number: 251 | Strong: true", "VERBS"),
    VocabularyWord("hochladen", "to upload", "-", emptyList(), "Number: 252 | Strong: true", "VERBS"),
    VocabularyWord("installieren", "to install", "-", emptyList(), "Number: 253", "VERBS"),
    VocabularyWord("aktualisieren", "to update", "-", emptyList(), "Number: 254", "VERBS"),
    VocabularyWord("starten", "to start (engine / IT)", "-", emptyList(), "Number: 255", "VERBS"),
    VocabularyWord("beenden", "to end / finish", "-", emptyList(), "Number: 256", "VERBS"),
    VocabularyWord("klicken", "to click", "-", emptyList(), "Number: 257", "VERBS"),
    VocabularyWord("wischen", "to wipe / swipe", "-", emptyList(), "Number: 258", "VERBS"),
    VocabularyWord("tippen", "to type / guess", "-", emptyList(), "Number: 259", "VERBS"),
    VocabularyWord("liken", "to like (social media)", "-", emptyList(), "Number: 260", "VERBS"),
    VocabularyWord("kommentieren", "to comment", "-", emptyList(), "Number: 261", "VERBS"),
    VocabularyWord("posten", "to post", "-", emptyList(), "Number: 262", "VERBS"),
    VocabularyWord("abonnieren", "to subscribe", "-", emptyList(), "Number: 263", "VERBS"),
    VocabularyWord("stornieren", "to cancel (order)", "-", emptyList(), "Number: 264", "VERBS"),
    VocabularyWord("zurücksenden", "to return (goods)", "-", emptyList(), "Number: 265 | Strong: true", "VERBS"),
    VocabularyWord("klären", "to clarify", "-", emptyList(), "Number: 266", "VERBS"),
    VocabularyWord("besprechen", "to discuss", "-", emptyList(), "Number: 267 | Strong: true", "VERBS"),
    VocabularyWord("diskutieren", "to discuss / debate", "-", emptyList(), "Number: 268", "VERBS"),
    VocabularyWord("argumentieren", "to argue (reason)", "-", emptyList(), "Number: 269", "VERBS"),
    VocabularyWord("überzeugen", "to convince", "-", emptyList(), "Number: 270", "VERBS"),
    VocabularyWord("überreden", "to persuade", "-", emptyList(), "Number: 271", "VERBS"),
    VocabularyWord("zweifeln an", "to doubt", "-", emptyList(), "Number: 272", "VERBS"),
    VocabularyWord("vertrauen", "to trust", "-", emptyList(), "Number: 273", "VERBS"),
    VocabularyWord("misstrauen", "to distrust", "-", emptyList(), "Number: 274", "VERBS"),
    VocabularyWord("hoffen auf", "to hope for", "-", emptyList(), "Number: 275", "VERBS"),
    VocabularyWord("fürchten", "to fear", "-", emptyList(), "Number: 276", "VERBS"),
    VocabularyWord("bereuen", "to regret", "-", emptyList(), "Number: 277", "VERBS"),
    VocabularyWord("genießen", "to enjoy", "-", emptyList(), "Number: 278 | Strong: true", "VERBS"),
    VocabularyWord("leiden an", "to suffer from", "-", emptyList(), "Number: 279 | Strong: true", "VERBS"),
    VocabularyWord("überleben", "to survive", "-", emptyList(), "Number: 280", "VERBS"),
    VocabularyWord("sterben", "to die", "-", emptyList(), "Number: 281 | Strong: true", "VERBS"),
    VocabularyWord("geboren werden", "to be born", "-", emptyList(), "Number: 282 | Strong: true", "VERBS"),
    VocabularyWord("aufwachsen", "to grow up", "-", emptyList(), "Number: 283 | Strong: true", "VERBS"),
    VocabularyWord("erziehen", "to bring up / educate", "-", emptyList(), "Number: 284 | Strong: true", "VERBS"),
    VocabularyWord("heiraten", "to marry", "-", emptyList(), "Number: 285", "VERBS"),
    VocabularyWord("scheiden", "to divorce / separate", "-", emptyList(), "Number: 286 | Strong: true", "VERBS"),
    VocabularyWord("verstehen", "to understand", "-", emptyList(), "Number: 287 | Strong: true", "VERBS"),
    VocabularyWord("übersetzen", "to translate", "-", emptyList(), "Number: 288", "VERBS"),
    VocabularyWord("aussprechen", "to pronounce", "-", emptyList(), "Number: 289 | Strong: true", "VERBS"),
    VocabularyWord("wiederholen", "to repeat", "-", emptyList(), "Number: 290", "VERBS"),
    VocabularyWord("üben", "to practice", "-", emptyList(), "Number: 291", "VERBS"),
    VocabularyWord("verbessern", "to improve", "-", emptyList(), "Number: 292", "VERBS"),
    VocabularyWord("korrigieren", "to correct", "-", emptyList(), "Number: 293", "VERBS"),
    VocabularyWord("ersetzen", "to replace", "-", emptyList(), "Number: 294", "VERBS"),
    VocabularyWord("hinzufügen", "to add", "-", emptyList(), "Number: 295", "VERBS"),
    VocabularyWord("entfernen", "to remove", "-", emptyList(), "Number: 296", "VERBS"),
    VocabularyWord("verschieben", "to postpone / move", "-", emptyList(), "Number: 297 | Strong: true", "VERBS"),
    VocabularyWord("absagen", "to cancel", "-", emptyList(), "Number: 298", "VERBS"),
    VocabularyWord("versprechen", "to promise", "-", emptyList(), "Number: 299 | Strong: true", "VERBS"),
    VocabularyWord("einhalten", "to keep (promise)", "-", emptyList(), "Number: 300 | Strong: true", "VERBS")
)
