package com.example

val top1000VocabularyData = listOf(
    VocabularyWord("sein", "to be", "-", emptyList(), "Number: 1", "TOP1000"),
    VocabularyWord("und", "and", "-", emptyList(), "Number: 2", "TOP1000"),
    VocabularyWord("der / die / das", "the", "-", emptyList(), "Number: 3", "TOP1000"),
    VocabularyWord("in", "in", "-", emptyList(), "Number: 4", "TOP1000"),
    VocabularyWord("ein / eine", "a/an", "-", emptyList(), "Number: 5", "TOP1000"),
    VocabularyWord("zu", "to, at", "-", emptyList(), "Number: 6", "TOP1000"),
    VocabularyWord("haben", "to have", "-", emptyList(), "Number: 7", "TOP1000"),
    VocabularyWord("ich", "I", "-", emptyList(), "Number: 8", "TOP1000"),
    VocabularyWord("werden", "to become, will", "-", emptyList(), "Number: 9", "TOP1000"),
    VocabularyWord("sie", "she, they", "-", emptyList(), "Number: 10", "TOP1000"),
    VocabularyWord("von", "from, of", "-", emptyList(), "Number: 11", "TOP1000"),
    VocabularyWord("nicht", "not", "-", emptyList(), "Number: 12", "TOP1000"),
    VocabularyWord("mit", "with", "-", emptyList(), "Number: 13", "TOP1000"),
    VocabularyWord("es", "it", "-", emptyList(), "Number: 14", "TOP1000"),
    VocabularyWord("sich", "oneself / themselves", "-", emptyList(), "Number: 15", "TOP1000"),
    VocabularyWord("auch", "also", "-", emptyList(), "Number: 16", "TOP1000"),
    VocabularyWord("auf", "on", "-", emptyList(), "Number: 17", "TOP1000"),
    VocabularyWord("für", "for", "-", emptyList(), "Number: 18", "TOP1000"),
    VocabularyWord("er", "he", "-", emptyList(), "Number: 19", "TOP1000"),
    VocabularyWord("als", "as, than", "-", emptyList(), "Number: 20", "TOP1000"),
    VocabularyWord("so", "so, thus", "-", emptyList(), "Number: 21", "TOP1000"),
    VocabularyWord("dass", "that (conj.)", "-", emptyList(), "Number: 22", "TOP1000"),
    VocabularyWord("können", "can", "-", emptyList(), "Number: 23", "TOP1000"),
    VocabularyWord("noch", "still, yet", "-", emptyList(), "Number: 24", "TOP1000"),
    VocabularyWord("an", "at, on", "-", emptyList(), "Number: 25", "TOP1000"),
    VocabularyWord("wie", "how", "-", emptyList(), "Number: 26", "TOP1000"),
    VocabularyWord("bei", "at, by", "-", emptyList(), "Number: 27", "TOP1000"),
    VocabularyWord("machen", "to do, make", "-", emptyList(), "Number: 28", "TOP1000"),
    VocabularyWord("wenn", "when, if", "-", emptyList(), "Number: 29", "TOP1000"),
    VocabularyWord("aber", "but", "-", emptyList(), "Number: 30", "TOP1000"),
    VocabularyWord("oder", "or", "-", emptyList(), "Number: 31", "TOP1000"),
    VocabularyWord("mehr", "more", "-", emptyList(), "Number: 32", "TOP1000"),
    VocabularyWord("was", "what", "-", emptyList(), "Number: 33", "TOP1000"),
    VocabularyWord("dieser", "this", "-", emptyList(), "Number: 34", "TOP1000"),
    VocabularyWord("immer", "always", "-", emptyList(), "Number: 35", "TOP1000"),
    VocabularyWord("gehen", "to go", "-", emptyList(), "Number: 36", "TOP1000"),
    VocabularyWord("sehr", "very", "-", emptyList(), "Number: 37", "TOP1000"),
    VocabularyWord("dann", "then", "-", emptyList(), "Number: 38", "TOP1000"),
    VocabularyWord("der Mann", "man", "-", emptyList(), "Number: 39", "TOP1000"),
    VocabularyWord("die Frau", "woman", "-", emptyList(), "Number: 40", "TOP1000"),
    VocabularyWord("das Kind", "child", "-", emptyList(), "Number: 41", "TOP1000"),
    VocabularyWord("die Zeit", "time", "-", emptyList(), "Number: 42", "TOP1000"),
    VocabularyWord("das Jahr", "year", "-", emptyList(), "Number: 43", "TOP1000"),
    VocabularyWord("der Tag", "day", "-", emptyList(), "Number: 44", "TOP1000"),
    VocabularyWord("die Hand", "hand", "-", emptyList(), "Number: 45", "TOP1000"),
    VocabularyWord("der Blick", "view, gaze", "-", emptyList(), "Number: 46", "TOP1000"),
    VocabularyWord("das Haus", "house", "-", emptyList(), "Number: 47", "TOP1000"),
    VocabularyWord("das Leben", "life", "-", emptyList(), "Number: 48", "TOP1000"),
    VocabularyWord("das Geld", "money", "-", emptyList(), "Number: 49", "TOP1000"),
    VocabularyWord("die Arbeit", "work", "-", emptyList(), "Number: 50", "TOP1000"),
    VocabularyWord("die Welt", "world", "-", emptyList(), "Number: 51", "TOP1000"),
    VocabularyWord("der Mensch", "human being", "-", emptyList(), "Number: 52", "TOP1000"),
    VocabularyWord("das Auge", "eye", "-", emptyList(), "Number: 53", "TOP1000"),
    VocabularyWord("die Frage", "question", "-", emptyList(), "Number: 54", "TOP1000"),
    VocabularyWord("groß", "big, tall", "-", emptyList(), "Number: 55", "TOP1000"),
    VocabularyWord("klein", "small, short", "-", emptyList(), "Number: 56", "TOP1000"),
    VocabularyWord("gut", "good", "-", emptyList(), "Number: 57", "TOP1000"),
    VocabularyWord("neu", "new", "-", emptyList(), "Number: 58", "TOP1000"),
    VocabularyWord("alt", "old", "-", emptyList(), "Number: 59", "TOP1000"),
    VocabularyWord("wollen", "to want", "-", emptyList(), "Number: 60", "TOP1000"),
    VocabularyWord("müssen", "must, have to", "-", emptyList(), "Number: 61", "TOP1000"),
    VocabularyWord("sollen", "should", "-", emptyList(), "Number: 62", "TOP1000"),
    VocabularyWord("kommen", "to come", "-", emptyList(), "Number: 63", "TOP1000"),
    VocabularyWord("geben", "to give", "-", emptyList(), "Number: 64", "TOP1000"),
    VocabularyWord("sagen", "to say", "-", emptyList(), "Number: 65", "TOP1000"),
    VocabularyWord("stehen", "to stand", "-", emptyList(), "Number: 66", "TOP1000"),
    VocabularyWord("finden", "to find", "-", emptyList(), "Number: 67", "TOP1000"),
    VocabularyWord("bleiben", "to stay", "-", emptyList(), "Number: 68", "TOP1000"),
    VocabularyWord("liegen", "to lie, be located", "-", emptyList(), "Number: 69", "TOP1000"),
    VocabularyWord("heißen", "to be called", "-", emptyList(), "Number: 70", "TOP1000"),
    VocabularyWord("denken", "to think", "-", emptyList(), "Number: 71", "TOP1000"),
    VocabularyWord("nehmen", "to take", "-", emptyList(), "Number: 72", "TOP1000"),
    VocabularyWord("tun", "to do", "-", emptyList(), "Number: 73", "TOP1000"),
    VocabularyWord("dürfen", "to be allowed", "-", emptyList(), "Number: 74", "TOP1000"),
    VocabularyWord("glauben", "to believe", "-", emptyList(), "Number: 75", "TOP1000"),
    VocabularyWord("halten", "to hold, stop", "-", emptyList(), "Number: 76", "TOP1000"),
    VocabularyWord("nennen", "to name", "-", emptyList(), "Number: 77", "TOP1000"),
    VocabularyWord("mögen", "to like", "-", emptyList(), "Number: 78", "TOP1000"),
    VocabularyWord("zeigen", "to show", "-", emptyList(), "Number: 79", "TOP1000"),
    VocabularyWord("führen", "to lead", "-", emptyList(), "Number: 80", "TOP1000"),
    VocabularyWord("sprechen", "to speak", "-", emptyList(), "Number: 81", "TOP1000"),
    VocabularyWord("bringen", "to bring", "-", emptyList(), "Number: 82", "TOP1000"),
    VocabularyWord("leben", "to live", "-", emptyList(), "Number: 83", "TOP1000"),
    VocabularyWord("fahren", "to drive, ride", "-", emptyList(), "Number: 84", "TOP1000"),
    VocabularyWord("lassen", "to let, leave", "-", emptyList(), "Number: 85", "TOP1000"),
    VocabularyWord("folgen", "to follow", "-", emptyList(), "Number: 86", "TOP1000"),
    VocabularyWord("lernen", "to learn", "-", emptyList(), "Number: 87", "TOP1000"),
    VocabularyWord("fragen", "to ask", "-", emptyList(), "Number: 88", "TOP1000"),
    VocabularyWord("antworten", "to answer", "-", emptyList(), "Number: 89", "TOP1000"),
    VocabularyWord("essen", "to eat", "-", emptyList(), "Number: 90", "TOP1000"),
    VocabularyWord("trinken", "to drink", "-", emptyList(), "Number: 91", "TOP1000"),
    VocabularyWord("schlafen", "to sleep", "-", emptyList(), "Number: 92", "TOP1000"),
    VocabularyWord("lesen", "to read", "-", emptyList(), "Number: 93", "TOP1000"),
    VocabularyWord("schreiben", "to write", "-", emptyList(), "Number: 94", "TOP1000"),
    VocabularyWord("laufen", "to run, walk", "-", emptyList(), "Number: 95", "TOP1000"),
    VocabularyWord("spielen", "to play", "-", emptyList(), "Number: 96", "TOP1000"),
    VocabularyWord("arbeiten", "to work", "-", emptyList(), "Number: 97", "TOP1000"),
    VocabularyWord("brauchen", "to need", "-", emptyList(), "Number: 98", "TOP1000"),
    VocabularyWord("erzählen", "to tell", "-", emptyList(), "Number: 99", "TOP1000"),
    VocabularyWord("versuchen", "to try", "-", emptyList(), "Number: 100", "TOP1000"),
    VocabularyWord("setzen", "to set, sit", "-", emptyList(), "Number: 101", "TOP1000"),
    VocabularyWord("bestehen", "to exist, pass", "-", emptyList(), "Number: 102", "TOP1000"),
    VocabularyWord("erklären", "to explain", "-", emptyList(), "Number: 103", "TOP1000"),
    VocabularyWord("erreichen", "to achieve, reach", "-", emptyList(), "Number: 104", "TOP1000"),
    VocabularyWord("schaffen", "to manage, create", "-", emptyList(), "Number: 105", "TOP1000"),
    VocabularyWord("entwickeln", "to develop", "-", emptyList(), "Number: 106", "TOP1000"),
    VocabularyWord("wünschen", "to wish", "-", emptyList(), "Number: 107", "TOP1000"),
    VocabularyWord("suchen", "to search", "-", emptyList(), "Number: 108", "TOP1000"),
    VocabularyWord("fehlen", "to be missing", "-", emptyList(), "Number: 109", "TOP1000"),
    VocabularyWord("bedeuten", "to mean", "-", emptyList(), "Number: 110", "TOP1000"),
    VocabularyWord("vergleichen", "to compare", "-", emptyList(), "Number: 111", "TOP1000"),
    VocabularyWord("verdienen", "to earn, deserve", "-", emptyList(), "Number: 112", "TOP1000"),
    VocabularyWord("wählen", "to choose, vote", "-", emptyList(), "Number: 113", "TOP1000"),
    VocabularyWord("ändern", "to change", "-", emptyList(), "Number: 114", "TOP1000"),
    VocabularyWord("prüfen", "to check", "-", emptyList(), "Number: 115", "TOP1000"),
    VocabularyWord("bilden", "to form, educate", "-", emptyList(), "Number: 116", "TOP1000"),
    VocabularyWord("betrachten", "to consider", "-", emptyList(), "Number: 117", "TOP1000"),
    VocabularyWord("unterstützen", "to support", "-", emptyList(), "Number: 118", "TOP1000"),
    VocabularyWord("kennen", "to know (person/place)", "-", emptyList(), "Number: 119", "TOP1000"),
    VocabularyWord("wissen", "to know (fact)", "-", emptyList(), "Number: 120", "TOP1000"),
    VocabularyWord("erinnern", "to remember", "-", emptyList(), "Number: 121", "TOP1000"),
    VocabularyWord("vorstellen", "to introduce, imagine", "-", emptyList(), "Number: 122", "TOP1000"),
    VocabularyWord("handeln", "to act, deal", "-", emptyList(), "Number: 123", "TOP1000"),
    VocabularyWord("sorgen", "to care, worry", "-", emptyList(), "Number: 124", "TOP1000"),
    VocabularyWord("fallen", "to fall", "-", emptyList(), "Number: 125", "TOP1000"),
    VocabularyWord("treffen", "to meet, hit", "-", emptyList(), "Number: 126", "TOP1000"),
    VocabularyWord("ziehen", "to pull", "-", emptyList(), "Number: 127", "TOP1000"),
    VocabularyWord("erwarten", "to expect", "-", emptyList(), "Number: 128", "TOP1000"),
    VocabularyWord("bestimmen", "to determine", "-", emptyList(), "Number: 129", "TOP1000"),
    VocabularyWord("besuchen", "to visit", "-", emptyList(), "Number: 130", "TOP1000"),
    VocabularyWord("beginnen", "to begin", "-", emptyList(), "Number: 131", "TOP1000"),
    VocabularyWord("gewinnen", "to win", "-", emptyList(), "Number: 132", "TOP1000"),
    VocabularyWord("verlieren", "to lose", "-", emptyList(), "Number: 133", "TOP1000"),
    VocabularyWord("tragen", "to carry, wear", "-", emptyList(), "Number: 134", "TOP1000"),
    VocabularyWord("kaufen", "to buy", "-", emptyList(), "Number: 135", "TOP1000"),
    VocabularyWord("verkaufen", "to sell", "-", emptyList(), "Number: 136", "TOP1000"),
    VocabularyWord("bezahlen", "to pay", "-", emptyList(), "Number: 137", "TOP1000"),
    VocabularyWord("bestellen", "to order", "-", emptyList(), "Number: 138", "TOP1000"),
    VocabularyWord("reservieren", "to reserve", "-", emptyList(), "Number: 139", "TOP1000"),
    VocabularyWord("buchen", "to book", "-", emptyList(), "Number: 140", "TOP1000"),
    VocabularyWord("reisen", "to travel", "-", emptyList(), "Number: 141", "TOP1000"),
    VocabularyWord("fliegen", "to fly", "-", emptyList(), "Number: 142", "TOP1000"),
    VocabularyWord("schwimmen", "to swim", "-", emptyList(), "Number: 143", "TOP1000"),
    VocabularyWord("singen", "to sing", "-", emptyList(), "Number: 144", "TOP1000"),
    VocabularyWord("tanzen", "to dance", "-", emptyList(), "Number: 145", "TOP1000"),
    VocabularyWord("kochen", "to cook", "-", emptyList(), "Number: 146", "TOP1000"),
    VocabularyWord("backen", "to bake", "-", emptyList(), "Number: 147", "TOP1000"),
    VocabularyWord("putzen", "to clean", "-", emptyList(), "Number: 148", "TOP1000"),
    VocabularyWord("waschen", "to wash", "-", emptyList(), "Number: 149", "TOP1000"),
    VocabularyWord("anziehen", "to dress, attract", "-", emptyList(), "Number: 150", "TOP1000"),
    VocabularyWord("ausziehen", "to undress, move out", "-", emptyList(), "Number: 151", "TOP1000"),
    VocabularyWord("umziehen", "to move house", "-", emptyList(), "Number: 152", "TOP1000"),
    VocabularyWord("öffnen", "to open", "-", emptyList(), "Number: 153", "TOP1000"),
    VocabularyWord("schließen", "to close", "-", emptyList(), "Number: 154", "TOP1000"),
    VocabularyWord("drücken", "to press", "-", emptyList(), "Number: 155", "TOP1000"),
    VocabularyWord("drehen", "to turn", "-", emptyList(), "Number: 156", "TOP1000"),
    VocabularyWord("legen", "to lay", "-", emptyList(), "Number: 157", "TOP1000"),
    VocabularyWord("stellen", "to put upright", "-", emptyList(), "Number: 158", "TOP1000"),
    VocabularyWord("hängen", "to hang", "-", emptyList(), "Number: 159", "TOP1000"),
    VocabularyWord("stecken", "to stick, put", "-", emptyList(), "Number: 160", "TOP1000"),
    VocabularyWord("holen", "to fetch", "-", emptyList(), "Number: 161", "TOP1000"),
    VocabularyWord("senden", "to send", "-", emptyList(), "Number: 162", "TOP1000"),
    VocabularyWord("empfangen", "to receive", "-", emptyList(), "Number: 163", "TOP1000"),
    VocabularyWord("teilen", "to share, divide", "-", emptyList(), "Number: 164", "TOP1000"),
    VocabularyWord("nutzen", "to use", "-", emptyList(), "Number: 165", "TOP1000"),
    VocabularyWord("benutzen", "to use", "-", emptyList(), "Number: 166", "TOP1000"),
    VocabularyWord("verwenden", "to use, apply", "-", emptyList(), "Number: 167", "TOP1000"),
    VocabularyWord("funktionieren", "to function", "-", emptyList(), "Number: 168", "TOP1000"),
    VocabularyWord("reparieren", "to repair", "-", emptyList(), "Number: 169", "TOP1000"),
    VocabularyWord("bauen", "to build", "-", emptyList(), "Number: 170", "TOP1000"),
    VocabularyWord("wohnen", "to live, reside", "-", emptyList(), "Number: 171", "TOP1000"),
    VocabularyWord("mieten", "to rent", "-", emptyList(), "Number: 172", "TOP1000"),
    VocabularyWord("besitzen", "to own", "-", emptyList(), "Number: 173", "TOP1000"),
    VocabularyWord("leihen", "to lend, borrow", "-", emptyList(), "Number: 174", "TOP1000"),
    VocabularyWord("schenken", "to give as a gift", "-", emptyList(), "Number: 175", "TOP1000"),
    VocabularyWord("einladen", "to invite", "-", emptyList(), "Number: 176", "TOP1000"),
    VocabularyWord("feiern", "to celebrate", "-", emptyList(), "Number: 177", "TOP1000"),
    VocabularyWord("gratulieren", "to congratulate", "-", emptyList(), "Number: 178", "TOP1000"),
    VocabularyWord("danken", "to thank", "-", emptyList(), "Number: 179", "TOP1000"),
    VocabularyWord("bitten", "to ask, request", "-", emptyList(), "Number: 180", "TOP1000"),
    VocabularyWord("hoffen", "to hope", "-", emptyList(), "Number: 181", "TOP1000"),
    VocabularyWord("lachen", "to laugh", "-", emptyList(), "Number: 182", "TOP1000"),
    VocabularyWord("weinen", "to cry", "-", emptyList(), "Number: 183", "TOP1000"),
    VocabularyWord("lächeln", "to smile", "-", emptyList(), "Number: 184", "TOP1000"),
    VocabularyWord("schreien", "to scream", "-", emptyList(), "Number: 185", "TOP1000"),
    VocabularyWord("flüstern", "to whisper", "-", emptyList(), "Number: 186", "TOP1000"),
    VocabularyWord("rufen", "to call", "-", emptyList(), "Number: 187", "TOP1000"),
    VocabularyWord("klingeln", "to ring", "-", emptyList(), "Number: 188", "TOP1000"),
    VocabularyWord("klopfen", "to knock", "-", emptyList(), "Number: 189", "TOP1000"),
    VocabularyWord("warten", "to wait", "-", emptyList(), "Number: 190", "TOP1000"),
    VocabularyWord("sich beeilen", "to hurry", "-", emptyList(), "Number: 191", "TOP1000"),
    VocabularyWord("sich ausruhen", "to rest", "-", emptyList(), "Number: 192", "TOP1000"),
    VocabularyWord("sich setzen", "to sit down", "-", emptyList(), "Number: 193", "TOP1000"),
    VocabularyWord("sich legen", "to lie down", "-", emptyList(), "Number: 194", "TOP1000"),
    VocabularyWord("sich kümmern", "to take care", "-", emptyList(), "Number: 195", "TOP1000"),
    VocabularyWord("sich treffen", "to meet", "-", emptyList(), "Number: 196", "TOP1000"),
    VocabularyWord("sich unterhalten", "to converse", "-", emptyList(), "Number: 197", "TOP1000"),
    VocabularyWord("das Beispiel", "example", "-", emptyList(), "Number: 198", "TOP1000"),
    VocabularyWord("die Möglichkeit", "possibility", "-", emptyList(), "Number: 199", "TOP1000"),
    VocabularyWord("die Art", "type, way", "-", emptyList(), "Number: 200", "TOP1000"),
    VocabularyWord("die Weise", "way, manner", "-", emptyList(), "Number: 201", "TOP1000"),
    VocabularyWord("der Grund", "reason", "-", emptyList(), "Number: 202", "TOP1000"),
    VocabularyWord("die Ursache", "cause", "-", emptyList(), "Number: 203", "TOP1000"),
    VocabularyWord("die Wirkung", "effect", "-", emptyList(), "Number: 204", "TOP1000"),
    VocabularyWord("der Unterschied", "difference", "-", emptyList(), "Number: 205", "TOP1000"),
    VocabularyWord("die Gemeinsamkeit", "commonality", "-", emptyList(), "Number: 206", "TOP1000"),
    VocabularyWord("die Veränderung", "change", "-", emptyList(), "Number: 207", "TOP1000"),
    VocabularyWord("die Entwicklung", "development", "-", emptyList(), "Number: 208", "TOP1000"),
    VocabularyWord("der Erfolg", "success", "-", emptyList(), "Number: 209", "TOP1000"),
    VocabularyWord("der Fehler", "mistake", "-", emptyList(), "Number: 210", "TOP1000"),
    VocabularyWord("die Lösung", "solution", "-", emptyList(), "Number: 211", "TOP1000"),
    VocabularyWord("das Problem", "problem", "-", emptyList(), "Number: 212", "TOP1000"),
    VocabularyWord("die Schwierigkeit", "difficulty", "-", emptyList(), "Number: 213", "TOP1000"),
    VocabularyWord("die Hilfe", "help", "-", emptyList(), "Number: 214", "TOP1000"),
    VocabularyWord("die Unterstützung", "support", "-", emptyList(), "Number: 215", "TOP1000"),
    VocabularyWord("die Information", "information", "-", emptyList(), "Number: 216", "TOP1000"),
    VocabularyWord("die Nachricht", "news, message", "-", emptyList(), "Number: 217", "TOP1000"),
    VocabularyWord("die Meinung", "opinion", "-", emptyList(), "Number: 218", "TOP1000"),
    VocabularyWord("die Erfahrung", "experience", "-", emptyList(), "Number: 219", "TOP1000"),
    VocabularyWord("die Kenntnis", "knowledge", "-", emptyList(), "Number: 220", "TOP1000"),
    VocabularyWord("das Wissen", "knowledge", "-", emptyList(), "Number: 221", "TOP1000"),
    VocabularyWord("die Bildung", "education", "-", emptyList(), "Number: 222", "TOP1000"),
    VocabularyWord("die Ausbildung", "training", "-", emptyList(), "Number: 223", "TOP1000"),
    VocabularyWord("der Beruf", "profession", "-", emptyList(), "Number: 224", "TOP1000"),
    VocabularyWord("die Stelle", "position, place", "-", emptyList(), "Number: 225", "TOP1000"),
    VocabularyWord("die Bewerbung", "application", "-", emptyList(), "Number: 226", "TOP1000"),
    VocabularyWord("das Vorstellungsgespräch", "job interview", "-", emptyList(), "Number: 227", "TOP1000"),
    VocabularyWord("der Vertrag", "contract", "-", emptyList(), "Number: 228", "TOP1000"),
    VocabularyWord("die Kündigung", "cancellation, resignation", "-", emptyList(), "Number: 229", "TOP1000"),
    VocabularyWord("die Freizeit", "leisure", "-", emptyList(), "Number: 230", "TOP1000"),
    VocabularyWord("der Urlaub", "vacation", "-", emptyList(), "Number: 231", "TOP1000"),
    VocabularyWord("die Reise", "trip", "-", emptyList(), "Number: 232", "TOP1000"),
    VocabularyWord("das Hotel", "hotel", "-", emptyList(), "Number: 233", "TOP1000"),
    VocabularyWord("das Zimmer", "room", "-", emptyList(), "Number: 234", "TOP1000"),
    VocabularyWord("das Bett", "bed", "-", emptyList(), "Number: 235", "TOP1000"),
    VocabularyWord("das Bad", "bathroom", "-", emptyList(), "Number: 236", "TOP1000"),
    VocabularyWord("die Küche", "kitchen", "-", emptyList(), "Number: 237", "TOP1000"),
    VocabularyWord("das Wohnzimmer", "living room", "-", emptyList(), "Number: 238", "TOP1000"),
    VocabularyWord("der Tisch", "table", "-", emptyList(), "Number: 239", "TOP1000"),
    VocabularyWord("der Stuhl", "chair", "-", emptyList(), "Number: 240", "TOP1000"),
    VocabularyWord("das Sofa", "sofa", "-", emptyList(), "Number: 241", "TOP1000"),
    VocabularyWord("der Schrank", "cupboard", "-", emptyList(), "Number: 242", "TOP1000"),
    VocabularyWord("das Regal", "shelf", "-", emptyList(), "Number: 243", "TOP1000"),
    VocabularyWord("die Lampe", "lamp", "-", emptyList(), "Number: 244", "TOP1000"),
    VocabularyWord("der Teppich", "carpet", "-", emptyList(), "Number: 245", "TOP1000"),
    VocabularyWord("das Bild", "picture", "-", emptyList(), "Number: 246", "TOP1000"),
    VocabularyWord("die Uhr", "clock, watch", "-", emptyList(), "Number: 247", "TOP1000"),
    VocabularyWord("die Stunde", "hour", "-", emptyList(), "Number: 248", "TOP1000"),
    VocabularyWord("die Minute", "minute", "-", emptyList(), "Number: 249", "TOP1000"),
    VocabularyWord("die Sekunde", "second", "-", emptyList(), "Number: 250", "TOP1000"),
    VocabularyWord("der Morgen", "morning", "-", emptyList(), "Number: 251", "TOP1000"),
    VocabularyWord("der Vormittag", "morning", "-", emptyList(), "Number: 252", "TOP1000"),
    VocabularyWord("der Mittag", "noon", "-", emptyList(), "Number: 253", "TOP1000"),
    VocabularyWord("der Nachmittag", "afternoon", "-", emptyList(), "Number: 254", "TOP1000"),
    VocabularyWord("der Abend", "evening", "-", emptyList(), "Number: 255", "TOP1000"),
    VocabularyWord("die Nacht", "night", "-", emptyList(), "Number: 256", "TOP1000"),
    VocabularyWord("der Montag", "Monday", "-", emptyList(), "Number: 257", "TOP1000"),
    VocabularyWord("der Dienstag", "Tuesday", "-", emptyList(), "Number: 258", "TOP1000"),
    VocabularyWord("der Mittwoch", "Wednesday", "-", emptyList(), "Number: 259", "TOP1000"),
    VocabularyWord("der Donnerstag", "Thursday", "-", emptyList(), "Number: 260", "TOP1000"),
    VocabularyWord("der Freitag", "Friday", "-", emptyList(), "Number: 261", "TOP1000"),
    VocabularyWord("der Samstag", "Saturday", "-", emptyList(), "Number: 262", "TOP1000"),
    VocabularyWord("der Sonntag", "Sunday", "-", emptyList(), "Number: 263", "TOP1000"),
    VocabularyWord("der Januar", "January", "-", emptyList(), "Number: 264", "TOP1000"),
    VocabularyWord("der Februar", "February", "-", emptyList(), "Number: 265", "TOP1000"),
    VocabularyWord("der März", "March", "-", emptyList(), "Number: 266", "TOP1000"),
    VocabularyWord("der April", "April", "-", emptyList(), "Number: 267", "TOP1000"),
    VocabularyWord("der Mai", "May", "-", emptyList(), "Number: 268", "TOP1000"),
    VocabularyWord("der Juni", "June", "-", emptyList(), "Number: 269", "TOP1000"),
    VocabularyWord("der Juli", "July", "-", emptyList(), "Number: 270", "TOP1000"),
    VocabularyWord("der August", "August", "-", emptyList(), "Number: 271", "TOP1000"),
    VocabularyWord("der September", "September", "-", emptyList(), "Number: 272", "TOP1000"),
    VocabularyWord("der Oktober", "October", "-", emptyList(), "Number: 273", "TOP1000"),
    VocabularyWord("der November", "November", "-", emptyList(), "Number: 274", "TOP1000"),
    VocabularyWord("der Dezember", "December", "-", emptyList(), "Number: 275", "TOP1000"),
    VocabularyWord("der Monat", "month", "-", emptyList(), "Number: 276", "TOP1000"),
    VocabularyWord("die Woche", "week", "-", emptyList(), "Number: 277", "TOP1000"),
    VocabularyWord("das Wochenende", "weekend", "-", emptyList(), "Number: 278", "TOP1000"),
    VocabularyWord("das Datum", "date", "-", emptyList(), "Number: 279", "TOP1000"),
    VocabularyWord("die Zahl", "number", "-", emptyList(), "Number: 280", "TOP1000"),
    VocabularyWord("die Nummer", "number", "-", emptyList(), "Number: 281", "TOP1000"),
    VocabularyWord("die Hälfte", "half", "-", emptyList(), "Number: 282", "TOP1000"),
    VocabularyWord("das Viertel", "quarter", "-", emptyList(), "Number: 283", "TOP1000"),
    VocabularyWord("das Prozent", "percent", "-", emptyList(), "Number: 284", "TOP1000"),
    VocabularyWord("der Euro", "euro", "-", emptyList(), "Number: 285", "TOP1000"),
    VocabularyWord("der Cent", "cent", "-", emptyList(), "Number: 286", "TOP1000"),
    VocabularyWord("die Rechnung", "bill, calculation", "-", emptyList(), "Number: 287", "TOP1000"),
    VocabularyWord("der Preis", "price", "-", emptyList(), "Number: 288", "TOP1000"),
    VocabularyWord("die Kosten", "costs", "-", emptyList(), "Number: 289", "TOP1000"),
    VocabularyWord("die Bank", "bank, bench", "-", emptyList(), "Number: 290", "TOP1000"),
    VocabularyWord("das Konto", "account", "-", emptyList(), "Number: 291", "TOP1000"),
    VocabularyWord("die Karte", "card, map, ticket", "-", emptyList(), "Number: 292", "TOP1000"),
    VocabularyWord("das Ticket", "ticket", "-", emptyList(), "Number: 293", "TOP1000"),
    VocabularyWord("die Fahrkarte", "travel ticket", "-", emptyList(), "Number: 294", "TOP1000"),
    VocabularyWord("der Fahrplan", "timetable", "-", emptyList(), "Number: 295", "TOP1000"),
    VocabularyWord("die Haltestelle", "stop", "-", emptyList(), "Number: 296", "TOP1000"),
    VocabularyWord("der Bahnhof", "train station", "-", emptyList(), "Number: 297", "TOP1000"),
    VocabularyWord("der Flughafen", "airport", "-", emptyList(), "Number: 298", "TOP1000"),
    VocabularyWord("das Gleis", "platform, track", "-", emptyList(), "Number: 299", "TOP1000"),
    VocabularyWord("der Zug", "train", "-", emptyList(), "Number: 300", "TOP1000"),
    VocabularyWord("der Bus", "bus", "-", emptyList(), "Number: 301", "TOP1000"),
    VocabularyWord("die S-Bahn", "suburban train", "-", emptyList(), "Number: 302", "TOP1000"),
    VocabularyWord("die U-Bahn", "subway", "-", emptyList(), "Number: 303", "TOP1000"),
    VocabularyWord("die Straßenbahn", "tram", "-", emptyList(), "Number: 304", "TOP1000"),
    VocabularyWord("das Auto", "car", "-", emptyList(), "Number: 305", "TOP1000"),
    VocabularyWord("das Fahrrad", "bicycle", "-", emptyList(), "Number: 306", "TOP1000"),
    VocabularyWord("das Motorrad", "motorcycle", "-", emptyList(), "Number: 307", "TOP1000"),
    VocabularyWord("der Lkw", "truck", "-", emptyList(), "Number: 308", "TOP1000"),
    VocabularyWord("die Straße", "street", "-", emptyList(), "Number: 309", "TOP1000"),
    VocabularyWord("die Autobahn", "highway", "-", emptyList(), "Number: 310", "TOP1000"),
    VocabularyWord("der Weg", "path, way", "-", emptyList(), "Number: 311", "TOP1000"),
    VocabularyWord("die Brücke", "bridge", "-", emptyList(), "Number: 312", "TOP1000"),
    VocabularyWord("der Fluss", "river", "-", emptyList(), "Number: 313", "TOP1000"),
    VocabularyWord("der See", "lake", "-", emptyList(), "Number: 314", "TOP1000"),
    VocabularyWord("das Meer", "sea", "-", emptyList(), "Number: 315", "TOP1000"),
    VocabularyWord("der Berg", "mountain", "-", emptyList(), "Number: 316", "TOP1000"),
    VocabularyWord("das Tal", "valley", "-", emptyList(), "Number: 317", "TOP1000"),
    VocabularyWord("der Wald", "forest", "-", emptyList(), "Number: 318", "TOP1000"),
    VocabularyWord("der Baum", "tree", "-", emptyList(), "Number: 319", "TOP1000"),
    VocabularyWord("die Blume", "flower", "-", emptyList(), "Number: 320", "TOP1000"),
    VocabularyWord("das Gras", "grass", "-", emptyList(), "Number: 321", "TOP1000"),
    VocabularyWord("die Sonne", "sun", "-", emptyList(), "Number: 322", "TOP1000"),
    VocabularyWord("der Mond", "moon", "-", emptyList(), "Number: 323", "TOP1000"),
    VocabularyWord("der Stern", "star", "-", emptyList(), "Number: 324", "TOP1000"),
    VocabularyWord("der Himmel", "sky, heaven", "-", emptyList(), "Number: 325", "TOP1000"),
    VocabularyWord("die Wolke", "cloud", "-", emptyList(), "Number: 326", "TOP1000"),
    VocabularyWord("der Regen", "rain", "-", emptyList(), "Number: 327", "TOP1000"),
    VocabularyWord("der Schnee", "snow", "-", emptyList(), "Number: 328", "TOP1000"),
    VocabularyWord("der Wind", "wind", "-", emptyList(), "Number: 329", "TOP1000"),
    VocabularyWord("die Kälte", "cold", "-", emptyList(), "Number: 330", "TOP1000"),
    VocabularyWord("die Hitze", "heat", "-", emptyList(), "Number: 331", "TOP1000"),
    VocabularyWord("die Temperatur", "temperature", "-", emptyList(), "Number: 332", "TOP1000"),
    VocabularyWord("das Wetter", "weather", "-", emptyList(), "Number: 333", "TOP1000"),
    VocabularyWord("die Natur", "nature", "-", emptyList(), "Number: 334", "TOP1000"),
    VocabularyWord("die Umwelt", "environment", "-", emptyList(), "Number: 335", "TOP1000"),
    VocabularyWord("das Tier", "animal", "-", emptyList(), "Number: 336", "TOP1000"),
    VocabularyWord("der Hund", "dog", "-", emptyList(), "Number: 337", "TOP1000"),
    VocabularyWord("die Katze", "cat", "-", emptyList(), "Number: 338", "TOP1000"),
    VocabularyWord("das Pferd", "horse", "-", emptyList(), "Number: 339", "TOP1000"),
    VocabularyWord("die Kuh", "cow", "-", emptyList(), "Number: 340", "TOP1000"),
    VocabularyWord("das Schwein", "pig", "-", emptyList(), "Number: 341", "TOP1000"),
    VocabularyWord("der Vogel", "bird", "-", emptyList(), "Number: 342", "TOP1000"),
    VocabularyWord("der Fisch", "fish", "-", emptyList(), "Number: 343", "TOP1000"),
    VocabularyWord("das Essen", "food", "-", emptyList(), "Number: 344", "TOP1000"),
    VocabularyWord("das Trinken", "drink", "-", emptyList(), "Number: 345", "TOP1000"),
    VocabularyWord("das Brot", "bread", "-", emptyList(), "Number: 346", "TOP1000"),
    VocabularyWord("das Brötchen", "roll", "-", emptyList(), "Number: 347", "TOP1000"),
    VocabularyWord("der Käse", "cheese", "-", emptyList(), "Number: 348", "TOP1000"),
    VocabularyWord("die Wurst", "sausage", "-", emptyList(), "Number: 349", "TOP1000"),
    VocabularyWord("das Fleisch", "meat", "-", emptyList(), "Number: 350", "TOP1000"),
    VocabularyWord("das Gemüse", "vegetable", "-", emptyList(), "Number: 351", "TOP1000"),
    VocabularyWord("das Obst", "fruit", "-", emptyList(), "Number: 352", "TOP1000"),
    VocabularyWord("die Kartoffel", "potato", "-", emptyList(), "Number: 353", "TOP1000"),
    VocabularyWord("die Nudeln", "noodles", "-", emptyList(), "Number: 354", "TOP1000"),
    VocabularyWord("der Reis", "rice", "-", emptyList(), "Number: 355", "TOP1000"),
    VocabularyWord("die Soße", "sauce", "-", emptyList(), "Number: 356", "TOP1000"),
    VocabularyWord("das Salz", "salt", "-", emptyList(), "Number: 357", "TOP1000"),
    VocabularyWord("der Pfeffer", "pepper", "-", emptyList(), "Number: 358", "TOP1000"),
    VocabularyWord("der Zucker", "sugar", "-", emptyList(), "Number: 359", "TOP1000"),
    VocabularyWord("die Butter", "butter", "-", emptyList(), "Number: 360", "TOP1000"),
    VocabularyWord("das Öl", "oil", "-", emptyList(), "Number: 361", "TOP1000"),
    VocabularyWord("die Milch", "milk", "-", emptyList(), "Number: 362", "TOP1000"),
    VocabularyWord("der Kaffee", "coffee", "-", emptyList(), "Number: 363", "TOP1000"),
    VocabularyWord("der Tee", "tea", "-", emptyList(), "Number: 364", "TOP1000"),
    VocabularyWord("das Wasser", "water", "-", emptyList(), "Number: 365", "TOP1000"),
    VocabularyWord("der Saft", "juice", "-", emptyList(), "Number: 366", "TOP1000"),
    VocabularyWord("das Bier", "beer", "-", emptyList(), "Number: 367", "TOP1000"),
    VocabularyWord("der Wein", "wine", "-", emptyList(), "Number: 368", "TOP1000"),
    VocabularyWord("der Alkohol", "alcohol", "-", emptyList(), "Number: 369", "TOP1000"),
    VocabularyWord("das Glas", "glass", "-", emptyList(), "Number: 370", "TOP1000"),
    VocabularyWord("die Tasse", "cup", "-", emptyList(), "Number: 371", "TOP1000"),
    VocabularyWord("die Flasche", "bottle", "-", emptyList(), "Number: 372", "TOP1000"),
    VocabularyWord("der Teller", "plate", "-", emptyList(), "Number: 373", "TOP1000"),
    VocabularyWord("die Gabel", "fork", "-", emptyList(), "Number: 374", "TOP1000"),
    VocabularyWord("das Messer", "knife", "-", emptyList(), "Number: 375", "TOP1000"),
    VocabularyWord("der Löffel", "spoon", "-", emptyList(), "Number: 376", "TOP1000"),
    VocabularyWord("der Topf", "pot", "-", emptyList(), "Number: 377", "TOP1000"),
    VocabularyWord("die Pfanne", "pan", "-", emptyList(), "Number: 378", "TOP1000"),
    VocabularyWord("der Herd", "stove", "-", emptyList(), "Number: 379", "TOP1000"),
    VocabularyWord("der Backofen", "oven", "-", emptyList(), "Number: 380", "TOP1000"),
    VocabularyWord("der Kühlschrank", "fridge", "-", emptyList(), "Number: 381", "TOP1000"),
    VocabularyWord("die Spülmaschine", "dishwasher", "-", emptyList(), "Number: 382", "TOP1000"),
    VocabularyWord("die Waschmaschine", "washing machine", "-", emptyList(), "Number: 383", "TOP1000"),
    VocabularyWord("der Staubsauger", "vacuum cleaner", "-", emptyList(), "Number: 384", "TOP1000"),
    VocabularyWord("das Bügeleisen", "iron", "-", emptyList(), "Number: 385", "TOP1000"),
    VocabularyWord("die Kleidung", "clothing", "-", emptyList(), "Number: 386", "TOP1000"),
    VocabularyWord("der Anzug", "suit", "-", emptyList(), "Number: 387", "TOP1000"),
    VocabularyWord("das Hemd", "shirt", "-", emptyList(), "Number: 388", "TOP1000"),
    VocabularyWord("die Bluse", "blouse", "-", emptyList(), "Number: 389", "TOP1000"),
    VocabularyWord("die Hose", "trousers", "-", emptyList(), "Number: 390", "TOP1000"),
    VocabularyWord("der Rock", "skirt", "-", emptyList(), "Number: 391", "TOP1000"),
    VocabularyWord("das Kleid", "dress", "-", emptyList(), "Number: 392", "TOP1000"),
    VocabularyWord("der Schuh", "shoe", "-", emptyList(), "Number: 393", "TOP1000"),
    VocabularyWord("der Stiefel", "boot", "-", emptyList(), "Number: 394", "TOP1000"),
    VocabularyWord("die Socke", "sock", "-", emptyList(), "Number: 395", "TOP1000"),
    VocabularyWord("die Strumpfhose", "tights", "-", emptyList(), "Number: 396", "TOP1000"),
    VocabularyWord("die Jacke", "jacket", "-", emptyList(), "Number: 397", "TOP1000"),
    VocabularyWord("der Mantel", "coat", "-", emptyList(), "Number: 398", "TOP1000"),
    VocabularyWord("der Pullover", "pullover", "-", emptyList(), "Number: 399", "TOP1000"),
    VocabularyWord("das T-Shirt", "t-shirt", "-", emptyList(), "Number: 400", "TOP1000"),
    VocabularyWord("die Mütze", "cap, hat", "-", emptyList(), "Number: 401", "TOP1000"),
    VocabularyWord("der Hut", "hat", "-", emptyList(), "Number: 402", "TOP1000"),
    VocabularyWord("der Schal", "scarf", "-", emptyList(), "Number: 403", "TOP1000"),
    VocabularyWord("der Handschuh", "glove", "-", emptyList(), "Number: 404", "TOP1000"),
    VocabularyWord("die Tasche", "bag, pocket", "-", emptyList(), "Number: 405", "TOP1000"),
    VocabularyWord("der Rucksack", "backpack", "-", emptyList(), "Number: 406", "TOP1000"),
    VocabularyWord("der Koffer", "suitcase", "-", emptyList(), "Number: 407", "TOP1000"),
    VocabularyWord("der Regenschirm", "umbrella", "-", emptyList(), "Number: 408", "TOP1000"),
    VocabularyWord("die Brille", "glasses", "-", emptyList(), "Number: 409", "TOP1000"),
    VocabularyWord("der Schmuck", "jewelry", "-", emptyList(), "Number: 410", "TOP1000"),
    VocabularyWord("der Ring", "ring", "-", emptyList(), "Number: 411", "TOP1000"),
    VocabularyWord("die Kette", "chain, necklace", "-", emptyList(), "Number: 412", "TOP1000"),
    VocabularyWord("das Parfüm", "perfume", "-", emptyList(), "Number: 413", "TOP1000"),
    VocabularyWord("die Creme", "cream", "-", emptyList(), "Number: 414", "TOP1000"),
    VocabularyWord("die Seife", "soap", "-", emptyList(), "Number: 415", "TOP1000"),
    VocabularyWord("das Shampoo", "shampoo", "-", emptyList(), "Number: 416", "TOP1000"),
    VocabularyWord("die Zahnbürste", "toothbrush", "-", emptyList(), "Number: 417", "TOP1000"),
    VocabularyWord("die Zahnpasta", "toothpaste", "-", emptyList(), "Number: 418", "TOP1000"),
    VocabularyWord("das Handtuch", "towel", "-", emptyList(), "Number: 419", "TOP1000"),
    VocabularyWord("der Spiegel", "mirror", "-", emptyList(), "Number: 420", "TOP1000"),
    VocabularyWord("der Kamm", "comb", "-", emptyList(), "Number: 421", "TOP1000"),
    VocabularyWord("die Bürste", "brush", "-", emptyList(), "Number: 422", "TOP1000"),
    VocabularyWord("die Schere", "scissors", "-", emptyList(), "Number: 423", "TOP1000"),
    VocabularyWord("der Föhn", "hairdryer", "-", emptyList(), "Number: 424", "TOP1000"),
    VocabularyWord("das Papier", "paper", "-", emptyList(), "Number: 425", "TOP1000"),
    VocabularyWord("der Kugelschreiber", "ballpoint pen", "-", emptyList(), "Number: 426", "TOP1000"),
    VocabularyWord("der Bleistift", "pencil", "-", emptyList(), "Number: 427", "TOP1000"),
    VocabularyWord("der Füller", "fountain pen", "-", emptyList(), "Number: 428", "TOP1000"),
    VocabularyWord("das Heft", "notebook", "-", emptyList(), "Number: 429", "TOP1000"),
    VocabularyWord("das Buch", "book", "-", emptyList(), "Number: 430", "TOP1000"),
    VocabularyWord("die Zeitung", "newspaper", "-", emptyList(), "Number: 431", "TOP1000"),
    VocabularyWord("die Zeitschrift", "magazine", "-", emptyList(), "Number: 432", "TOP1000"),
    VocabularyWord("der Brief", "letter", "-", emptyList(), "Number: 433", "TOP1000"),
    VocabularyWord("die Post", "mail", "-", emptyList(), "Number: 434", "TOP1000"),
    VocabularyWord("die Briefmarke", "stamp", "-", emptyList(), "Number: 435", "TOP1000"),
    VocabularyWord("das Päckchen", "parcel", "-", emptyList(), "Number: 436", "TOP1000"),
    VocabularyWord("das Paket", "package", "-", emptyList(), "Number: 437", "TOP1000"),
    VocabularyWord("die Nachricht", "message", "-", emptyList(), "Number: 438", "TOP1000"),
    VocabularyWord("das Telefon", "telephone", "-", emptyList(), "Number: 439", "TOP1000"),
    VocabularyWord("das Handy", "mobile phone", "-", emptyList(), "Number: 440", "TOP1000"),
    VocabularyWord("der Computer", "computer", "-", emptyList(), "Number: 441", "TOP1000"),
    VocabularyWord("das Tablet", "tablet", "-", emptyList(), "Number: 442", "TOP1000"),
    VocabularyWord("der Laptop", "laptop", "-", emptyList(), "Number: 443", "TOP1000"),
    VocabularyWord("der Bildschirm", "screen", "-", emptyList(), "Number: 444", "TOP1000"),
    VocabularyWord("die Tastatur", "keyboard", "-", emptyList(), "Number: 445", "TOP1000"),
    VocabularyWord("die Maus", "mouse", "-", emptyList(), "Number: 446", "TOP1000"),
    VocabularyWord("der Drucker", "printer", "-", emptyList(), "Number: 447", "TOP1000"),
    VocabularyWord("das Internet", "internet", "-", emptyList(), "Number: 448", "TOP1000"),
    VocabularyWord("die E-Mail", "email", "-", emptyList(), "Number: 449", "TOP1000"),
    VocabularyWord("die Webseite", "website", "-", emptyList(), "Number: 450", "TOP1000"),
    VocabularyWord("die App", "app", "-", emptyList(), "Number: 451", "TOP1000"),
    VocabularyWord("die Kamera", "camera", "-", emptyList(), "Number: 452", "TOP1000"),
    VocabularyWord("das Foto", "photo", "-", emptyList(), "Number: 453", "TOP1000"),
    VocabularyWord("das Video", "video", "-", emptyList(), "Number: 454", "TOP1000"),
    VocabularyWord("der Film", "film", "-", emptyList(), "Number: 455", "TOP1000"),
    VocabularyWord("die Musik", "music", "-", emptyList(), "Number: 456", "TOP1000"),
    VocabularyWord("das Lied", "song", "-", emptyList(), "Number: 457", "TOP1000"),
    VocabularyWord("das Radio", "radio", "-", emptyList(), "Number: 458", "TOP1000"),
    VocabularyWord("der Fernseher", "television set", "-", emptyList(), "Number: 459", "TOP1000"),
    VocabularyWord("die Sendung", "programme, broadcast", "-", emptyList(), "Number: 460", "TOP1000"),
    VocabularyWord("die Werbung", "advertising", "-", emptyList(), "Number: 461", "TOP1000"),
    VocabularyWord("die Nachrichten", "news", "-", emptyList(), "Number: 462", "TOP1000"),
    VocabularyWord("die Politik", "politics", "-", emptyList(), "Number: 463", "TOP1000"),
    VocabularyWord("die Regierung", "government", "-", emptyList(), "Number: 464", "TOP1000"),
    VocabularyWord("das Gesetz", "law", "-", emptyList(), "Number: 465", "TOP1000"),
    VocabularyWord("die Polizei", "police", "-", emptyList(), "Number: 466", "TOP1000"),
    VocabularyWord("der Arzt", "doctor", "-", emptyList(), "Number: 467", "TOP1000"),
    VocabularyWord("das Krankenhaus", "hospital", "-", emptyList(), "Number: 468", "TOP1000"),
    VocabularyWord("die Apotheke", "pharmacy", "-", emptyList(), "Number: 469", "TOP1000"),
    VocabularyWord("das Medikament", "medicine", "-", emptyList(), "Number: 470", "TOP1000"),
    VocabularyWord("die Krankenversicherung", "health insurance", "-", emptyList(), "Number: 471", "TOP1000"),
    VocabularyWord("der Schmerz", "pain", "-", emptyList(), "Number: 472", "TOP1000"),
    VocabularyWord("die Krankheit", "illness", "-", emptyList(), "Number: 473", "TOP1000"),
    VocabularyWord("die Gesundheit", "health", "-", emptyList(), "Number: 474", "TOP1000"),
    VocabularyWord("das Fieber", "fever", "-", emptyList(), "Number: 475", "TOP1000"),
    VocabularyWord("der Husten", "cough", "-", emptyList(), "Number: 476", "TOP1000"),
    VocabularyWord("der Schnupfen", "runny nose", "-", emptyList(), "Number: 477", "TOP1000"),
    VocabularyWord("die Erkältung", "cold", "-", emptyList(), "Number: 478", "TOP1000"),
    VocabularyWord("die Allergie", "allergy", "-", emptyList(), "Number: 479", "TOP1000"),
    VocabularyWord("der Termin", "appointment", "-", emptyList(), "Number: 480", "TOP1000"),
    VocabularyWord("das Rezept", "prescription, recipe", "-", emptyList(), "Number: 481", "TOP1000"),
    VocabularyWord("die Tablette", "pill", "-", emptyList(), "Number: 482", "TOP1000"),
    VocabularyWord("die Salbe", "ointment", "-", emptyList(), "Number: 483", "TOP1000"),
    VocabularyWord("die Spritze", "injection", "-", emptyList(), "Number: 484", "TOP1000"),
    VocabularyWord("die Operation", "operation", "-", emptyList(), "Number: 485", "TOP1000"),
    VocabularyWord("der Unfall", "accident", "-", emptyList(), "Number: 486", "TOP1000"),
    VocabularyWord("der Notfall", "emergency", "-", emptyList(), "Number: 487", "TOP1000"),
    VocabularyWord("die Feuerwehr", "fire department", "-", emptyList(), "Number: 488", "TOP1000"),
    VocabularyWord("der Krankenwagen", "ambulance", "-", emptyList(), "Number: 489", "TOP1000"),
    VocabularyWord("die Drogerie", "drugstore", "-", emptyList(), "Number: 490", "TOP1000"),
    VocabularyWord("der Supermarkt", "supermarket", "-", emptyList(), "Number: 491", "TOP1000"),
    VocabularyWord("die Bäckerei", "bakery", "-", emptyList(), "Number: 492", "TOP1000"),
    VocabularyWord("die Metzgerei", "butcher", "-", emptyList(), "Number: 493", "TOP1000"),
    VocabularyWord("der Markt", "market", "-", emptyList(), "Number: 494", "TOP1000"),
    VocabularyWord("das Einkaufszentrum", "shopping centre", "-", emptyList(), "Number: 495", "TOP1000"),
    VocabularyWord("das Geschäft", "shop, business", "-", emptyList(), "Number: 496", "TOP1000"),
    VocabularyWord("der Laden", "shop", "-", emptyList(), "Number: 497", "TOP1000"),
    VocabularyWord("das Kaufhaus", "department store", "-", emptyList(), "Number: 498", "TOP1000"),
    VocabularyWord("die Kasse", "cash register, checkout", "-", emptyList(), "Number: 499", "TOP1000"),
    VocabularyWord("der Einkauf", "purchase", "-", emptyList(), "Number: 500", "TOP1000")
)
