package com.example

val topListsVocabularyData = listOf(
    // Collocations
    VocabularyWord("eine Entscheidung treffen", "to make a decision", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Verantwortung übernehmen", "to take responsibility", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("eine Rolle spielen", "to play a role", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("zur Verfügung stehen", "to be available", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("in Frage kommen", "to come into question / be considered", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Rücksicht nehmen auf", "to take into account", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("einen Fehler machen / begehen", "to make a mistake", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("einen Kompromiss schließen", "to compromise", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("in der Lage sein", "to be able to", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Wert legen auf", "to value / attach importance to", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Gebrauch machen von", "to make use of", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("eine Frage stellen", "to ask a question", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Antwort geben", "to give an answer", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Hilfe leisten", "to provide help", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("ein Gespräch führen", "to conduct a conversation", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Kritik üben", "to criticise", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Lob aussprechen", "to express praise", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("einen Vorschlag machen", "to make a suggestion", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("eine Vereinbarung treffen", "to make an agreement", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("eine Rede halten", "to give a speech", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("einen Vortrag halten", "to give a lecture", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("zur Welt bringen", "to give birth", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("in Erfüllung gehen", "to come true", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("außer Acht lassen", "to disregard", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("in Betracht ziehen", "to consider", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Maßnahmen ergreifen", "to take measures", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Schaden zufügen", "to cause damage", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("einen Beitrag leisten", "to make a contribution", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("sich Mühe geben", "to make an effort", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("einen Antrag stellen", "to submit an application", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("ein Konto eröffnen", "to open an account", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("eine Rechnung bezahlen", "to pay a bill", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("ein Ticket buchen", "to book a ticket", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("eine Reservierung vornehmen", "to make a reservation", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("ein Formular ausfüllen", "to fill in a form", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("eine Diät halten", "to stick to a diet", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Sport treiben", "to do sports", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("eine Pause machen", "to take a break", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Zeit verbringen", "to spend time", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Geduld haben", "to have patience", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Angst haben vor", "to be afraid of", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Mut zeigen", "to show courage", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("einen Blick werfen auf", "to take a look at", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("in Kontakt bleiben", "to stay in touch", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("zur Kenntnis nehmen", "to take note of", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("in Angriff nehmen", "to tackle", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("zu Ende bringen", "to finish / bring to an end", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("in Bewegung setzen", "to set in motion", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("außer Kraft setzen", "to override / invalidate", "-", emptyList(), "Category: Collocations", "LISTS"),
    VocabularyWord("Bescheid wissen", "to know about / be informed", "-", emptyList(), "Category: Collocations", "LISTS"),

    // Idioms
    VocabularyWord("Tomaten auf den Augen haben", "to be oblivious (lit. to have tomatoes on one's eyes)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("Ich verstehe nur Bahnhof.", "I don't understand a thing (lit. I only understand train station)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("Daumen drücken!", "Fingers crossed! (lit. press thumbs)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("sich zum Affen machen", "to make a fool of oneself", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("das ist mir Wurst", "I couldn't care less (lit. that's sausage to me)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("die Nase voll haben von", "to be fed up with (lit. to have the nose full of)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("ins Fettnäpfchen treten", "to put one's foot in it (lit. to step into the little fat bowl)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("den Nagel auf den Kopf treffen", "to hit the nail on the head", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("Schnee von gestern", "old hat (lit. yesterday's snow)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("in den sauren Apfel beißen", "to bite the bullet (lit. to bite into the sour apple)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("das Handtuch werfen", "to throw in the towel", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("mit dem Feuer spielen", "to play with fire", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("den Teufel an die Wand malen", "to prophesy doom (lit. to paint the devil on the wall)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("sich keine grauen Haare wachsen lassen", "not to worry (lit. not to let grey hairs grow)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("das Kind mit dem Bade ausschütten", "to throw the baby out with the bathwater", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("ein Wink mit dem Zaunpfahl", "a broad hint (lit. a hint with a fence post)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("die Kirche im Dorf lassen", "not to get carried away (lit. leave the church in the village)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("Perlen vor die Säue werfen", "to cast pearls before swine", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("den Bock zum Gärtner machen", "to let the fox guard the henhouse (lit. to make the goat the gardener)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("jemandem Honig ums Maul schmieren", "to butter someone up (lit. to smear honey around someone's mouth)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("sich ein Bein ausreißen", "to bend over backwards (lit. to tear off a leg)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("auf dünnem Eis wandeln", "to skate on thin ice", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("unter die Arme greifen", "to lend a hand (lit. to grab under the arms)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("aus dem Nähkästchen plaudern", "to spill secrets (lit. to chatter out of the sewing box)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("ein Schlag ins Gesicht", "a slap in the face (fig. a severe blow)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("mit offenen Karten spielen", "to be upfront (lit. to play with open cards)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("alles in Butter", "everything's fine (lit. everything in butter)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("das Leben ist kein Ponyhof", "life isn't a bed of roses (lit. life is not a pony farm)", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("ich drücke dir die Daumen", "I'm keeping my fingers crossed for you", "-", emptyList(), "Category: Idioms", "LISTS"),
    VocabularyWord("Da beißt sich die Katze in den Schwanz.", "It's a vicious circle.", "-", emptyList(), "Category: Idioms", "LISTS"),

    // Connectors
    VocabularyWord("und", "and", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("oder", "or", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("aber", "but", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("denn", "because (coord.)", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("weil", "because (sub.)", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("dass", "that", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("wenn", "when / if", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("als", "when (past single event)", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("bevor", "before", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("nachdem", "after", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("sobald", "as soon as", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("seit / seitdem", "since", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("während", "while / during", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("obwohl", "although", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("trotzdem", "nevertheless (adv.)", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("deshalb / daher / darum", "therefore", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("so dass / sodass", "so that", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("indem", "by …-ing", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("falls", "in case / if", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("außer wenn", "unless", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("es sei denn, dass", "unless (formal)", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("geschweige denn", "let alone", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("wohingegen", "whereas", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("allerdings", "however", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("dennoch", "nevertheless (elevated)", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("insofern (als)", "insofar as", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("infolgedessen", "consequently", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("unter der Voraussetzung, dass", "provided that", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("vorausgesetzt, dass", "assuming that", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("nicht nur ... sondern auch", "not only ... but also", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("entweder ... oder", "either ... or", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("weder ... noch", "neither ... nor", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("einerseits ... andererseits", "on the one hand ... on the other hand", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("zunächst", "first of all", "-", emptyList(), "Category: Connectors", "LISTS"),
    VocabularyWord("schließlich", "finally / after all", "-", emptyList(), "Category: Connectors", "LISTS"),

    // Business Expressions
    VocabularyWord("das Meeting", "meeting", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Besprechung", "meeting (more formal)", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("der Termin", "appointment", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Deadline", "deadline", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Präsentation", "presentation", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Tagesordnung", "agenda", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("das Protokoll", "minutes", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("der Bericht", "report", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Analyse", "analysis", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Strategie", "strategy", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("das Projekt", "project", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Aufgabe", "task", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("das Ziel", "goal / objective", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Deadline einhalten", "to meet the deadline", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("eine Besprechung abhalten / einberufen", "to hold / call a meeting", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("ein Projekt leiten", "to manage a project", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("Verantwortung übernehmen", "to take responsibility", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("eine Entscheidung treffen", "to make a decision", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("in Frage kommen", "to come into question", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("Maßnahmen ergreifen", "to take measures", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("zur Verfügung stehen", "to be available", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("Rücksprache halten", "to consult (with someone)", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("einen Vertrag abschließen", "to conclude a contract", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("eine Vereinbarung treffen", "to make an agreement", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Frist verlängern", "to extend the deadline", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("in Verhandlung stehen", "to be in negotiation", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("ein Angebot einholen", "to obtain a quote", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("eine Rechnung stellen", "to issue an invoice", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Kosten übernehmen", "to cover the costs", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("eine Präsentation halten", "to give a presentation", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("Feedback geben", "to give feedback", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("Kritik üben", "to criticise (professionally)", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("jemanden in CC setzen", "to CC someone", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("den Stand der Dinge mitteilen", "to give a status update", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("das Geschäftsjahr", "financial year", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("der Umsatz", "turnover", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("der Gewinn", "profit", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("der Verlust", "loss", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Bilanz", "balance sheet", "-", emptyList(), "Category: Business", "LISTS"),
    VocabularyWord("die Aktie", "share", "-", emptyList(), "Category: Business", "LISTS"),

    // Academic Expressions
    VocabularyWord("die Hypothese", "hypothesis", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die These", "thesis", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die Theorie", "theory", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("das Phänomen", "phenomenon", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("der Ansatz", "approach", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die Methodik", "methodology", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die empirische Studie", "empirical study", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die Daten erheben", "to collect data", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("eine Umfrage durchführen", "to conduct a survey", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die Stichprobe", "sample", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die Variable", "variable", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die Auswertung", "evaluation", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die Schlussfolgerung", "conclusion", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("das Fazit", "conclusion / summary", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("etwas in Betracht ziehen", "to consider sth.", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("einer Frage nachgehen", "to investigate a question", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("einen Beweis erbringen", "to provide proof", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("eine Behauptung widerlegen", "to refute a claim", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("übereinstimmen mit", "to agree with / correspond to", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("im Widerspruch stehen zu", "to contradict", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("auf etwas eingehen", "to go into / address sth.", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("den Fokus legen auf", "to focus on", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("einen Schwerpunkt setzen", "to set a priority", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("zusammenfassend lässt sich sagen", "in summary, it can be said", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("es ist hervorzuheben, dass", "it must be emphasised that", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("daraus ergibt sich, dass", "it follows that", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("im Vergleich zu", "in comparison to", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("im Gegensatz zu", "in contrast to", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("unter Berücksichtigung", "taking into account", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("vor diesem Hintergrund", "against this background", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("in Anlehnung an", "following / based on", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("das Konzept beruht auf", "the concept is based on", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("die Arbeit gliedert sich in", "the paper is divided into", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("ferner / des Weiteren", "furthermore", "-", emptyList(), "Category: Academic", "LISTS"),
    VocabularyWord("abschließend", "in conclusion", "-", emptyList(), "Category: Academic", "LISTS")
)
