package com.example

val top1000VocabularyDataPart2 = listOf(
    VocabularyWord("die Tüte", "bag", "-", emptyList(), "Number: 501", "TOP1000"),
    VocabularyWord("der Korb", "basket", "-", emptyList(), "Number: 502", "TOP1000"),
    VocabularyWord("der Einkaufswagen", "shopping cart", "-", emptyList(), "Number: 503", "TOP1000"),
    VocabularyWord("die Kreditkarte", "credit card", "-", emptyList(), "Number: 504", "TOP1000"),
    VocabularyWord("die EC-Karte", "debit card", "-", emptyList(), "Number: 505", "TOP1000"),
    VocabularyWord("das Bargeld", "cash", "-", emptyList(), "Number: 506", "TOP1000"),
    VocabularyWord("die Quittung", "receipt", "-", emptyList(), "Number: 507", "TOP1000"),
    VocabularyWord("der Kunde", "customer", "-", emptyList(), "Number: 508", "TOP1000"),
    VocabularyWord("die Verkäuferin", "saleswoman", "-", emptyList(), "Number: 509", "TOP1000"),
    VocabularyWord("der Verkäufer", "salesman", "-", emptyList(), "Number: 510", "TOP1000"),
    VocabularyWord("die Größe", "size", "-", emptyList(), "Number: 511", "TOP1000"),
    VocabularyWord("die Farbe", "colour", "-", emptyList(), "Number: 512", "TOP1000"),
    VocabularyWord("die Qualität", "quality", "-", emptyList(), "Number: 513", "TOP1000"),
    VocabularyWord("der Rabatt", "discount", "-", emptyList(), "Number: 514", "TOP1000"),
    VocabularyWord("das Sonderangebot", "special offer", "-", emptyList(), "Number: 515", "TOP1000"),
    VocabularyWord("die Garantie", "guarantee", "-", emptyList(), "Number: 516", "TOP1000"),
    VocabularyWord("der Umtausch", "exchange", "-", emptyList(), "Number: 517", "TOP1000"),
    VocabularyWord("die Reklamation", "complaint", "-", emptyList(), "Number: 518", "TOP1000"),
    VocabularyWord("die Bestellung", "order", "-", emptyList(), "Number: 519", "TOP1000"),
    VocabularyWord("die Lieferung", "delivery", "-", emptyList(), "Number: 520", "TOP1000"),
    VocabularyWord("der Versand", "shipping", "-", emptyList(), "Number: 521", "TOP1000"),
    VocabularyWord("die Telefonnummer", "telephone number", "-", emptyList(), "Number: 522", "TOP1000"),
    VocabularyWord("die Adresse", "address", "-", emptyList(), "Number: 523", "TOP1000"),
    VocabularyWord("der Name", "name", "-", emptyList(), "Number: 524", "TOP1000"),
    VocabularyWord("der Vorname", "first name", "-", emptyList(), "Number: 525", "TOP1000"),
    VocabularyWord("der Nachname", "last name", "-", emptyList(), "Number: 526", "TOP1000"),
    VocabularyWord("das Geburtsdatum", "date of birth", "-", emptyList(), "Number: 527", "TOP1000"),
    VocabularyWord("der Geburtsort", "place of birth", "-", emptyList(), "Number: 528", "TOP1000"),
    VocabularyWord("die Nationalität", "nationality", "-", emptyList(), "Number: 529", "TOP1000"),
    VocabularyWord("die Staatsangehörigkeit", "citizenship", "-", emptyList(), "Number: 530", "TOP1000"),
    VocabularyWord("der Familienstand", "marital status", "-", emptyList(), "Number: 531", "TOP1000"),
    VocabularyWord("ledig", "single", "-", emptyList(), "Number: 532", "TOP1000"),
    VocabularyWord("verheiratet", "married", "-", emptyList(), "Number: 533", "TOP1000"),
    VocabularyWord("geschieden", "divorced", "-", emptyList(), "Number: 534", "TOP1000"),
    VocabularyWord("verwitwet", "widowed", "-", emptyList(), "Number: 535", "TOP1000"),
    VocabularyWord("der Partner", "partner", "-", emptyList(), "Number: 536", "TOP1000"),
    VocabularyWord("die Ehefrau", "wife", "-", emptyList(), "Number: 537", "TOP1000"),
    VocabularyWord("der Ehemann", "husband", "-", emptyList(), "Number: 538", "TOP1000"),
    VocabularyWord("die Eltern", "parents", "-", emptyList(), "Number: 539", "TOP1000"),
    VocabularyWord("die Mutter", "mother", "-", emptyList(), "Number: 540", "TOP1000"),
    VocabularyWord("der Vater", "father", "-", emptyList(), "Number: 541", "TOP1000"),
    VocabularyWord("die Tochter", "daughter", "-", emptyList(), "Number: 542", "TOP1000"),
    VocabularyWord("der Sohn", "son", "-", emptyList(), "Number: 543", "TOP1000"),
    VocabularyWord("die Schwester", "sister", "-", emptyList(), "Number: 544", "TOP1000"),
    VocabularyWord("der Bruder", "brother", "-", emptyList(), "Number: 545", "TOP1000"),
    VocabularyWord("die Großeltern", "grandparents", "-", emptyList(), "Number: 546", "TOP1000"),
    VocabularyWord("die Oma", "grandma", "-", emptyList(), "Number: 547", "TOP1000"),
    VocabularyWord("der Opa", "grandpa", "-", emptyList(), "Number: 548", "TOP1000"),
    VocabularyWord("die Enkel", "grandchildren", "-", emptyList(), "Number: 549", "TOP1000"),
    VocabularyWord("die Tante", "aunt", "-", emptyList(), "Number: 550", "TOP1000"),
    VocabularyWord("der Onkel", "uncle", "-", emptyList(), "Number: 551", "TOP1000"),
    VocabularyWord("die Cousine", "female cousin", "-", emptyList(), "Number: 552", "TOP1000"),
    VocabularyWord("der Cousin", "male cousin", "-", emptyList(), "Number: 553", "TOP1000"),
    VocabularyWord("der Freund", "friend, boyfriend", "-", emptyList(), "Number: 554", "TOP1000"),
    VocabularyWord("die Freundin", "girlfriend, female friend", "-", emptyList(), "Number: 555", "TOP1000"),
    VocabularyWord("der Bekannte", "acquaintance", "-", emptyList(), "Number: 556", "TOP1000"),
    VocabularyWord("der Nachbar", "neighbour", "-", emptyList(), "Number: 557", "TOP1000"),
    VocabularyWord("der Mitbewohner", "flatmate", "-", emptyList(), "Number: 558", "TOP1000"),
    VocabularyWord("der Kollege", "colleague", "-", emptyList(), "Number: 559", "TOP1000"),
    VocabularyWord("der Chef", "boss", "-", emptyList(), "Number: 560", "TOP1000"),
    VocabularyWord("der Mitarbeiter", "employee", "-", emptyList(), "Number: 561", "TOP1000"),
    VocabularyWord("das Team", "team", "-", emptyList(), "Number: 562", "TOP1000"),
    VocabularyWord("die Besprechung", "meeting", "-", emptyList(), "Number: 563", "TOP1000"),
    VocabularyWord("die Konferenz", "conference", "-", emptyList(), "Number: 564", "TOP1000"),
    VocabularyWord("die Tagesordnung", "agenda", "-", emptyList(), "Number: 565", "TOP1000"),
    VocabularyWord("das Protokoll", "minutes, protocol", "-", emptyList(), "Number: 566", "TOP1000"),
    VocabularyWord("die Präsentation", "presentation", "-", emptyList(), "Number: 567", "TOP1000"),
    VocabularyWord("der Vortrag", "lecture, presentation", "-", emptyList(), "Number: 568", "TOP1000"),
    VocabularyWord("das Projekt", "project", "-", emptyList(), "Number: 569", "TOP1000"),
    VocabularyWord("die Aufgabe", "task", "-", emptyList(), "Number: 570", "TOP1000"),
    VocabularyWord("das Ziel", "goal", "-", emptyList(), "Number: 571", "TOP1000"),
    VocabularyWord("der Plan", "plan", "-", emptyList(), "Number: 572", "TOP1000"),
    VocabularyWord("die Idee", "idea", "-", emptyList(), "Number: 573", "TOP1000"),
    VocabularyWord("der Vorschlag", "suggestion", "-", emptyList(), "Number: 574", "TOP1000"),
    VocabularyWord("die Entscheidung", "decision", "-", emptyList(), "Number: 575", "TOP1000"),
    VocabularyWord("die Lösung", "solution", "-", emptyList(), "Number: 576", "TOP1000"),
    VocabularyWord("das Ergebnis", "result", "-", emptyList(), "Number: 577", "TOP1000"),
    VocabularyWord("der Bericht", "report", "-", emptyList(), "Number: 578", "TOP1000"),
    VocabularyWord("die Analyse", "analysis", "-", emptyList(), "Number: 579", "TOP1000"),
    VocabularyWord("die Statistik", "statistics", "-", emptyList(), "Number: 580", "TOP1000"),
    VocabularyWord("die Grafik", "graphic, chart", "-", emptyList(), "Number: 581", "TOP1000"),
    VocabularyWord("die Tabelle", "table", "-", emptyList(), "Number: 582", "TOP1000"),
    VocabularyWord("die Vereinbarung", "agreement", "-", emptyList(), "Number: 583", "TOP1000"),
    VocabularyWord("die Bedingung", "condition", "-", emptyList(), "Number: 584", "TOP1000"),
    VocabularyWord("die Frist", "deadline", "-", emptyList(), "Number: 585", "TOP1000"),
    VocabularyWord("die Verlängerung", "extension", "-", emptyList(), "Number: 586", "TOP1000"),
    VocabularyWord("die Anmeldung", "registration", "-", emptyList(), "Number: 587", "TOP1000"),
    VocabularyWord("die Abmeldung", "deregistration", "-", emptyList(), "Number: 588", "TOP1000"),
    VocabularyWord("das Formular", "form", "-", emptyList(), "Number: 589", "TOP1000"),
    VocabularyWord("der Antrag", "application", "-", emptyList(), "Number: 590", "TOP1000"),
    VocabularyWord("die Genehmigung", "approval, permit", "-", emptyList(), "Number: 591", "TOP1000"),
    VocabularyWord("die Unterschrift", "signature", "-", emptyList(), "Number: 592", "TOP1000"),
    VocabularyWord("die Kopie", "copy", "-", emptyList(), "Number: 593", "TOP1000"),
    VocabularyWord("der Ausweis", "ID", "-", emptyList(), "Number: 594", "TOP1000"),
    VocabularyWord("der Personalausweis", "identity card", "-", emptyList(), "Number: 595", "TOP1000"),
    VocabularyWord("der Reisepass", "passport", "-", emptyList(), "Number: 596", "TOP1000"),
    VocabularyWord("das Visum", "visa", "-", emptyList(), "Number: 597", "TOP1000"),
    VocabularyWord("die Behörde", "authority", "-", emptyList(), "Number: 598", "TOP1000"),
    VocabularyWord("das Amt", "office, authority", "-", emptyList(), "Number: 599", "TOP1000"),
    VocabularyWord("der Beamte", "civil servant", "-", emptyList(), "Number: 600", "TOP1000"),
    VocabularyWord("die Steuer", "tax", "-", emptyList(), "Number: 601", "TOP1000"),
    VocabularyWord("die Versicherung", "insurance", "-", emptyList(), "Number: 602", "TOP1000"),
    VocabularyWord("die Haftpflicht", "liability", "-", emptyList(), "Number: 603", "TOP1000"),
    VocabularyWord("der Rechtsschutz", "legal protection", "-", emptyList(), "Number: 604", "TOP1000"),
    VocabularyWord("die Rente", "pension", "-", emptyList(), "Number: 605", "TOP1000"),
    VocabularyWord("die Sozialhilfe", "social welfare", "-", emptyList(), "Number: 606", "TOP1000"),
    VocabularyWord("die Arbeitslosigkeit", "unemployment", "-", emptyList(), "Number: 607", "TOP1000"),
    VocabularyWord("das Arbeitsamt", "job centre", "-", emptyList(), "Number: 608", "TOP1000"),
    VocabularyWord("die Gewerkschaft", "trade union", "-", emptyList(), "Number: 609", "TOP1000"),
    VocabularyWord("der Tarifvertrag", "wage agreement", "-", emptyList(), "Number: 610", "TOP1000"),
    VocabularyWord("das Gehalt", "salary", "-", emptyList(), "Number: 611", "TOP1000"),
    VocabularyWord("der Lohn", "wage", "-", emptyList(), "Number: 612", "TOP1000"),
    VocabularyWord("die Bezahlung", "payment", "-", emptyList(), "Number: 613", "TOP1000"),
    VocabularyWord("die Lohnabrechnung", "payslip", "-", emptyList(), "Number: 614", "TOP1000"),
    VocabularyWord("die Überstunde", "overtime", "-", emptyList(), "Number: 615", "TOP1000"),
    VocabularyWord("die Krankmeldung", "sick note", "-", emptyList(), "Number: 616", "TOP1000"),
    VocabularyWord("die Kündigungsfrist", "notice period", "-", emptyList(), "Number: 617", "TOP1000"),
    VocabularyWord("das Arbeitszeugnis", "reference letter", "-", emptyList(), "Number: 618", "TOP1000"),
    VocabularyWord("die Arbeitssuche", "job search", "-", emptyList(), "Number: 619", "TOP1000"),
    VocabularyWord("das Stellengesuch", "job advertisement", "-", emptyList(), "Number: 620", "TOP1000"),
    VocabularyWord("die Initiativbewerbung", "speculative application", "-", emptyList(), "Number: 621", "TOP1000"),
    VocabularyWord("die Zusage", "acceptance", "-", emptyList(), "Number: 622", "TOP1000"),
    VocabularyWord("die Absage", "rejection", "-", emptyList(), "Number: 623", "TOP1000"),
    VocabularyWord("der Misserfolg", "failure", "-", emptyList(), "Number: 624", "TOP1000"),
    VocabularyWord("die Chance", "chance, opportunity", "-", emptyList(), "Number: 625", "TOP1000"),
    VocabularyWord("das Glück", "luck, happiness", "-", emptyList(), "Number: 626", "TOP1000"),
    VocabularyWord("das Pech", "bad luck", "-", emptyList(), "Number: 627", "TOP1000"),
    VocabularyWord("die Hoffnung", "hope", "-", emptyList(), "Number: 628", "TOP1000"),
    VocabularyWord("die Angst", "fear", "-", emptyList(), "Number: 629", "TOP1000"),
    VocabularyWord("die Freude", "joy", "-", emptyList(), "Number: 630", "TOP1000"),
    VocabularyWord("die Traurigkeit", "sadness", "-", emptyList(), "Number: 631", "TOP1000"),
    VocabularyWord("die Wut", "anger", "-", emptyList(), "Number: 632", "TOP1000"),
    VocabularyWord("die Liebe", "love", "-", emptyList(), "Number: 633", "TOP1000"),
    VocabularyWord("der Hass", "hate", "-", emptyList(), "Number: 634", "TOP1000"),
    VocabularyWord("das Mitleid", "pity", "-", emptyList(), "Number: 635", "TOP1000"),
    VocabularyWord("die Scham", "shame", "-", emptyList(), "Number: 636", "TOP1000"),
    VocabularyWord("die Schuld", "guilt", "-", emptyList(), "Number: 637", "TOP1000"),
    VocabularyWord("die Eifersucht", "jealousy", "-", emptyList(), "Number: 638", "TOP1000"),
    VocabularyWord("die Enttäuschung", "disappointment", "-", emptyList(), "Number: 639", "TOP1000"),
    VocabularyWord("die Erleichterung", "relief", "-", emptyList(), "Number: 640", "TOP1000"),
    VocabularyWord("die Überraschung", "surprise", "-", emptyList(), "Number: 641", "TOP1000"),
    VocabularyWord("die Verwirrung", "confusion", "-", emptyList(), "Number: 642", "TOP1000"),
    VocabularyWord("die Neugierde", "curiosity", "-", emptyList(), "Number: 643", "TOP1000"),
    VocabularyWord("die Begeisterung", "enthusiasm", "-", emptyList(), "Number: 644", "TOP1000"),
    VocabularyWord("der Stolz", "pride", "-", emptyList(), "Number: 645", "TOP1000"),
    VocabularyWord("die Dankbarkeit", "gratitude", "-", emptyList(), "Number: 646", "TOP1000"),
    VocabularyWord("der Respekt", "respect", "-", emptyList(), "Number: 647", "TOP1000"),
    VocabularyWord("das Vertrauen", "trust", "-", emptyList(), "Number: 648", "TOP1000"),
    VocabularyWord("die Sorge", "worry", "-", emptyList(), "Number: 649", "TOP1000"),
    VocabularyWord("die Geduld", "patience", "-", emptyList(), "Number: 650", "TOP1000"),
    VocabularyWord("die Ungeduld", "impatience", "-", emptyList(), "Number: 651", "TOP1000"),
    VocabularyWord("die Ruhe", "calm, quiet", "-", emptyList(), "Number: 652", "TOP1000"),
    VocabularyWord("die Unruhe", "restlessness", "-", emptyList(), "Number: 653", "TOP1000"),
    VocabularyWord("die Kraft", "strength, power", "-", emptyList(), "Number: 654", "TOP1000"),
    VocabularyWord("die Schwäche", "weakness", "-", emptyList(), "Number: 655", "TOP1000"),
    VocabularyWord("die Energie", "energy", "-", emptyList(), "Number: 656", "TOP1000"),
    VocabularyWord("die Müdigkeit", "tiredness", "-", emptyList(), "Number: 657", "TOP1000"),
    VocabularyWord("das Wohlbefinden", "well-being", "-", emptyList(), "Number: 658", "TOP1000"),
    VocabularyWord("die Ernährung", "nutrition", "-", emptyList(), "Number: 659", "TOP1000"),
    VocabularyWord("die Bewegung", "exercise, movement", "-", emptyList(), "Number: 660", "TOP1000"),
    VocabularyWord("die Entspannung", "relaxation", "-", emptyList(), "Number: 661", "TOP1000"),
    VocabularyWord("der Stress", "stress", "-", emptyList(), "Number: 662", "TOP1000"),
    VocabularyWord("die Meditation", "meditation", "-", emptyList(), "Number: 663", "TOP1000"),
    VocabularyWord("die Therapie", "therapy", "-", emptyList(), "Number: 664", "TOP1000"),
    VocabularyWord("die Beratung", "counseling, advice", "-", emptyList(), "Number: 665", "TOP1000"),
    VocabularyWord("die Förderung", "promotion, funding", "-", emptyList(), "Number: 666", "TOP1000"),
    VocabularyWord("die Verbesserung", "improvement", "-", emptyList(), "Number: 667", "TOP1000"),
    VocabularyWord("die Verschlechterung", "deterioration", "-", emptyList(), "Number: 668", "TOP1000"),
    VocabularyWord("die Zunahme", "increase", "-", emptyList(), "Number: 669", "TOP1000"),
    VocabularyWord("die Abnahme", "decrease", "-", emptyList(), "Number: 670", "TOP1000"),
    VocabularyWord("der Anstieg", "rise", "-", emptyList(), "Number: 671", "TOP1000"),
    VocabularyWord("der Rückgang", "decline", "-", emptyList(), "Number: 672", "TOP1000"),
    VocabularyWord("der Wandel", "change", "-", emptyList(), "Number: 673", "TOP1000"),
    VocabularyWord("die Stabilität", "stability", "-", emptyList(), "Number: 674", "TOP1000"),
    VocabularyWord("die Instabilität", "instability", "-", emptyList(), "Number: 675", "TOP1000"),
    VocabularyWord("die Sicherheit", "safety, security", "-", emptyList(), "Number: 676", "TOP1000"),
    VocabularyWord("die Unsicherheit", "uncertainty", "-", emptyList(), "Number: 677", "TOP1000"),
    VocabularyWord("die Gefahr", "danger", "-", emptyList(), "Number: 678", "TOP1000"),
    VocabularyWord("das Risiko", "risk", "-", emptyList(), "Number: 679", "TOP1000"),
    VocabularyWord("der Schutz", "protection", "-", emptyList(), "Number: 680", "TOP1000"),
    VocabularyWord("die Vorsicht", "caution", "-", emptyList(), "Number: 681", "TOP1000"),
    VocabularyWord("die Achtung", "attention, respect", "-", emptyList(), "Number: 682", "TOP1000"),
    VocabularyWord("die Warnung", "warning", "-", emptyList(), "Number: 683", "TOP1000"),
    VocabularyWord("die Erlaubnis", "permission", "-", emptyList(), "Number: 684", "TOP1000"),
    VocabularyWord("das Verbot", "ban", "-", emptyList(), "Number: 685", "TOP1000"),
    VocabularyWord("die Regel", "rule", "-", emptyList(), "Number: 686", "TOP1000"),
    VocabularyWord("die Vorschrift", "regulation", "-", emptyList(), "Number: 687", "TOP1000"),
    VocabularyWord("das Recht", "right, law", "-", emptyList(), "Number: 688", "TOP1000"),
    VocabularyWord("die Pflicht", "duty", "-", emptyList(), "Number: 689", "TOP1000"),
    VocabularyWord("die Freiheit", "freedom", "-", emptyList(), "Number: 690", "TOP1000"),
    VocabularyWord("die Gleichheit", "equality", "-", emptyList(), "Number: 691", "TOP1000"),
    VocabularyWord("die Gerechtigkeit", "justice", "-", emptyList(), "Number: 692", "TOP1000"),
    VocabularyWord("die Ungerechtigkeit", "injustice", "-", emptyList(), "Number: 693", "TOP1000"),
    VocabularyWord("die Demokratie", "democracy", "-", emptyList(), "Number: 694", "TOP1000"),
    VocabularyWord("die Diktatur", "dictatorship", "-", emptyList(), "Number: 695", "TOP1000"),
    VocabularyWord("die Wahl", "election, choice", "-", emptyList(), "Number: 696", "TOP1000"),
    VocabularyWord("die Abstimmung", "vote, coordination", "-", emptyList(), "Number: 697", "TOP1000"),
    VocabularyWord("die Partei", "party", "-", emptyList(), "Number: 698", "TOP1000"),
    VocabularyWord("die Opposition", "opposition", "-", emptyList(), "Number: 699", "TOP1000"),
    VocabularyWord("der Politiker", "politician", "-", emptyList(), "Number: 700", "TOP1000"),
    VocabularyWord("der Präsident", "president", "-", emptyList(), "Number: 701", "TOP1000"),
    VocabularyWord("der Kanzler", "chancellor", "-", emptyList(), "Number: 702", "TOP1000"),
    VocabularyWord("der Minister", "minister", "-", emptyList(), "Number: 703", "TOP1000"),
    VocabularyWord("das Parlament", "parliament", "-", emptyList(), "Number: 704", "TOP1000"),
    VocabularyWord("die Verwaltung", "administration", "-", emptyList(), "Number: 705", "TOP1000"),
    VocabularyWord("der Bürger", "citizen", "-", emptyList(), "Number: 706", "TOP1000"),
    VocabularyWord("die Gesellschaft", "society", "-", emptyList(), "Number: 707", "TOP1000"),
    VocabularyWord("die Öffentlichkeit", "public", "-", emptyList(), "Number: 708", "TOP1000"),
    VocabularyWord("die Medien", "media", "-", emptyList(), "Number: 709", "TOP1000"),
    VocabularyWord("die Presse", "press", "-", emptyList(), "Number: 710", "TOP1000"),
    VocabularyWord("der Journalist", "journalist", "-", emptyList(), "Number: 711", "TOP1000"),
    VocabularyWord("die Reportage", "reportage", "-", emptyList(), "Number: 712", "TOP1000"),
    VocabularyWord("das Interview", "interview", "-", emptyList(), "Number: 713", "TOP1000"),
    VocabularyWord("die Diskussion", "discussion", "-", emptyList(), "Number: 714", "TOP1000"),
    VocabularyWord("die Debatte", "debate", "-", emptyList(), "Number: 715", "TOP1000"),
    VocabularyWord("der Kommentar", "commentary", "-", emptyList(), "Number: 716", "TOP1000"),
    VocabularyWord("die Kritik", "criticism", "-", emptyList(), "Number: 717", "TOP1000"),
    VocabularyWord("die Meinungsfreiheit", "freedom of speech", "-", emptyList(), "Number: 718", "TOP1000"),
    VocabularyWord("die Zensur", "censorship", "-", emptyList(), "Number: 719", "TOP1000"),
    VocabularyWord("die Propaganda", "propaganda", "-", emptyList(), "Number: 720", "TOP1000"),
    VocabularyWord("die Wahrheit", "truth", "-", emptyList(), "Number: 721", "TOP1000"),
    VocabularyWord("die Lüge", "lie", "-", emptyList(), "Number: 722", "TOP1000"),
    VocabularyWord("das Gerücht", "rumour", "-", emptyList(), "Number: 723", "TOP1000"),
    VocabularyWord("die Tatsache", "fact", "-", emptyList(), "Number: 724", "TOP1000"),
    VocabularyWord("die Behauptung", "claim", "-", emptyList(), "Number: 725", "TOP1000"),
    VocabularyWord("der Beweis", "proof", "-", emptyList(), "Number: 726", "TOP1000"),
    VocabularyWord("das Argument", "argument", "-", emptyList(), "Number: 727", "TOP1000"),
    VocabularyWord("das Gegenargument", "counter-argument", "-", emptyList(), "Number: 728", "TOP1000"),
    VocabularyWord("der Schluss", "conclusion", "-", emptyList(), "Number: 729", "TOP1000"),
    VocabularyWord("die Schlussfolgerung", "conclusion", "-", emptyList(), "Number: 730", "TOP1000"),
    VocabularyWord("die Logik", "logic", "-", emptyList(), "Number: 731", "TOP1000"),
    VocabularyWord("der Widerspruch", "contradiction", "-", emptyList(), "Number: 732", "TOP1000"),
    VocabularyWord("die Übereinstimmung", "agreement", "-", emptyList(), "Number: 733", "TOP1000"),
    VocabularyWord("der Kompromiss", "compromise", "-", emptyList(), "Number: 734", "TOP1000"),
    VocabularyWord("der Konflikt", "conflict", "-", emptyList(), "Number: 735", "TOP1000"),
    VocabularyWord("der Krieg", "war", "-", emptyList(), "Number: 736", "TOP1000"),
    VocabularyWord("der Frieden", "peace", "-", emptyList(), "Number: 737", "TOP1000"),
    VocabularyWord("die Gewalt", "violence", "-", emptyList(), "Number: 738", "TOP1000"),
    VocabularyWord("die Aggression", "aggression", "-", emptyList(), "Number: 739", "TOP1000"),
    VocabularyWord("die Toleranz", "tolerance", "-", emptyList(), "Number: 740", "TOP1000"),
    VocabularyWord("die Intoleranz", "intolerance", "-", emptyList(), "Number: 741", "TOP1000"),
    VocabularyWord("die Akzeptanz", "acceptance", "-", emptyList(), "Number: 742", "TOP1000"),
    VocabularyWord("die Diskriminierung", "discrimination", "-", emptyList(), "Number: 743", "TOP1000"),
    VocabularyWord("der Rassismus", "racism", "-", emptyList(), "Number: 744", "TOP1000"),
    VocabularyWord("der Sexismus", "sexism", "-", emptyList(), "Number: 745", "TOP1000"),
    VocabularyWord("die Gleichberechtigung", "equality of rights", "-", emptyList(), "Number: 746", "TOP1000"),
    VocabularyWord("die Integration", "integration", "-", emptyList(), "Number: 747", "TOP1000"),
    VocabularyWord("die Inklusion", "inclusion", "-", emptyList(), "Number: 748", "TOP1000"),
    VocabularyWord("die Exklusion", "exclusion", "-", emptyList(), "Number: 749", "TOP1000"),
    VocabularyWord("die Diversität", "diversity", "-", emptyList(), "Number: 750", "TOP1000"),
    VocabularyWord("die Kultur", "culture", "-", emptyList(), "Number: 751", "TOP1000"),
    VocabularyWord("die Tradition", "tradition", "-", emptyList(), "Number: 752", "TOP1000"),
    VocabularyWord("die Geschichte", "history, story", "-", emptyList(), "Number: 753", "TOP1000"),
    VocabularyWord("die Vergangenheit", "past", "-", emptyList(), "Number: 754", "TOP1000"),
    VocabularyWord("die Gegenwart", "present", "-", emptyList(), "Number: 755", "TOP1000"),
    VocabularyWord("die Zukunft", "future", "-", emptyList(), "Number: 756", "TOP1000"),
    VocabularyWord("die Erinnerung", "memory", "-", emptyList(), "Number: 757", "TOP1000"),
    VocabularyWord("die Weisheit", "wisdom", "-", emptyList(), "Number: 758", "TOP1000"),
    VocabularyWord("die Erziehung", "upbringing", "-", emptyList(), "Number: 759", "TOP1000"),
    VocabularyWord("das Lernen", "learning", "-", emptyList(), "Number: 760", "TOP1000"),
    VocabularyWord("die Lehre", "teaching, apprenticeship", "-", emptyList(), "Number: 761", "TOP1000"),
    VocabularyWord("die Wissenschaft", "science", "-", emptyList(), "Number: 762", "TOP1000"),
    VocabularyWord("die Technik", "technology, technique", "-", emptyList(), "Number: 763", "TOP1000"),
    VocabularyWord("die Innovation", "innovation", "-", emptyList(), "Number: 764", "TOP1000"),
    VocabularyWord("die Erfindung", "invention", "-", emptyList(), "Number: 765", "TOP1000"),
    VocabularyWord("die Entdeckung", "discovery", "-", emptyList(), "Number: 766", "TOP1000"),
    VocabularyWord("der Fortschritt", "progress", "-", emptyList(), "Number: 767", "TOP1000"),
    VocabularyWord("der Rückschritt", "regression", "-", emptyList(), "Number: 768", "TOP1000"),
    VocabularyWord("die Modernisierung", "modernization", "-", emptyList(), "Number: 769", "TOP1000"),
    VocabularyWord("die Globalisierung", "globalization", "-", emptyList(), "Number: 770", "TOP1000"),
    VocabularyWord("die Digitalisierung", "digitalization", "-", emptyList(), "Number: 771", "TOP1000"),
    VocabularyWord("die Vernetzung", "networking", "-", emptyList(), "Number: 772", "TOP1000"),
    VocabularyWord("die Kommunikation", "communication", "-", emptyList(), "Number: 773", "TOP1000"),
    VocabularyWord("die Interaktion", "interaction", "-", emptyList(), "Number: 774", "TOP1000"),
    VocabularyWord("die Beziehung", "relationship", "-", emptyList(), "Number: 775", "TOP1000"),
    VocabularyWord("die Partnerschaft", "partnership", "-", emptyList(), "Number: 776", "TOP1000"),
    VocabularyWord("die Freundschaft", "friendship", "-", emptyList(), "Number: 777", "TOP1000"),
    VocabularyWord("der Verrat", "betrayal", "-", emptyList(), "Number: 778", "TOP1000"),
    VocabularyWord("die Leidenschaft", "passion", "-", emptyList(), "Number: 779", "TOP1000"),
    VocabularyWord("die Emotion", "emotion", "-", emptyList(), "Number: 780", "TOP1000"),
    VocabularyWord("das Gefühl", "feeling", "-", emptyList(), "Number: 781", "TOP1000"),
    VocabularyWord("die Stimmung", "mood", "-", emptyList(), "Number: 782", "TOP1000"),
    VocabularyWord("die Laune", "mood, whim", "-", emptyList(), "Number: 783", "TOP1000"),
    VocabularyWord("die Atmosphäre", "atmosphere", "-", emptyList(), "Number: 784", "TOP1000"),
    VocabularyWord("die Umgebung", "surroundings", "-", emptyList(), "Number: 785", "TOP1000"),
    VocabularyWord("die Landschaft", "landscape", "-", emptyList(), "Number: 786", "TOP1000"),
    VocabularyWord("die Verschmutzung", "pollution", "-", emptyList(), "Number: 787", "TOP1000"),
    VocabularyWord("der Klimawandel", "climate change", "-", emptyList(), "Number: 788", "TOP1000"),
    VocabularyWord("die Erderwärmung", "global warming", "-", emptyList(), "Number: 789", "TOP1000"),
    VocabularyWord("die Nachhaltigkeit", "sustainability", "-", emptyList(), "Number: 790", "TOP1000"),
    VocabularyWord("die erneuerbare Energie", "renewable energy", "-", emptyList(), "Number: 791", "TOP1000"),
    VocabularyWord("die Solarenergie", "solar energy", "-", emptyList(), "Number: 792", "TOP1000"),
    VocabularyWord("die Windenergie", "wind energy", "-", emptyList(), "Number: 793", "TOP1000"),
    VocabularyWord("die Wasserkraft", "water power", "-", emptyList(), "Number: 794", "TOP1000"),
    VocabularyWord("die Kernenergie", "nuclear energy", "-", emptyList(), "Number: 795", "TOP1000"),
    VocabularyWord("die Kohle", "coal", "-", emptyList(), "Number: 796", "TOP1000"),
    VocabularyWord("das Gas", "gas", "-", emptyList(), "Number: 797", "TOP1000"),
    VocabularyWord("der Strom", "electricity", "-", emptyList(), "Number: 798", "TOP1000"),
    VocabularyWord("der Verbrauch", "consumption", "-", emptyList(), "Number: 799", "TOP1000"),
    VocabularyWord("die Effizienz", "efficiency", "-", emptyList(), "Number: 800", "TOP1000"),
    VocabularyWord("die Einsparung", "saving", "-", emptyList(), "Number: 801", "TOP1000"),
    VocabularyWord("der Müll", "garbage", "-", emptyList(), "Number: 802", "TOP1000"),
    VocabularyWord("das Recycling", "recycling", "-", emptyList(), "Number: 803", "TOP1000"),
    VocabularyWord("der Abfall", "waste", "-", emptyList(), "Number: 804", "TOP1000"),
    VocabularyWord("die Wiederverwertung", "re-utilization", "-", emptyList(), "Number: 805", "TOP1000"),
    VocabularyWord("der Biomüll", "bio-waste", "-", emptyList(), "Number: 806", "TOP1000"),
    VocabularyWord("der Restmüll", "residual waste", "-", emptyList(), "Number: 807", "TOP1000"),
    VocabularyWord("der gelbe Sack", "yellow bag (packaging recycling)", "-", emptyList(), "Number: 808", "TOP1000"),
    VocabularyWord("die blaue Tonne", "blue bin (paper)", "-", emptyList(), "Number: 809", "TOP1000"),
    VocabularyWord("der Altglascontainer", "glass container", "-", emptyList(), "Number: 810", "TOP1000"),
    VocabularyWord("der Sondermüll", "hazardous waste", "-", emptyList(), "Number: 811", "TOP1000"),
    VocabularyWord("die Deponie", "landfill", "-", emptyList(), "Number: 812", "TOP1000"),
    VocabularyWord("die Verbrennung", "incineration", "-", emptyList(), "Number: 813", "TOP1000"),
    VocabularyWord("die Kompostierung", "composting", "-", emptyList(), "Number: 814", "TOP1000"),
    VocabularyWord("die Kreislaufwirtschaft", "circular economy", "-", emptyList(), "Number: 815", "TOP1000"),
    VocabularyWord("die Artenvielfalt", "biodiversity", "-", emptyList(), "Number: 816", "TOP1000"),
    VocabularyWord("der Artenschutz", "species protection", "-", emptyList(), "Number: 817", "TOP1000"),
    VocabularyWord("der Tierschutz", "animal protection", "-", emptyList(), "Number: 818", "TOP1000"),
    VocabularyWord("der Regenwald", "rainforest", "-", emptyList(), "Number: 819", "TOP1000"),
    VocabularyWord("die Abholzung", "deforestation", "-", emptyList(), "Number: 820", "TOP1000"),
    VocabularyWord("die Wüstenbildung", "desertification", "-", emptyList(), "Number: 821", "TOP1000"),
    VocabularyWord("der Meeresspiegel", "sea level", "-", emptyList(), "Number: 822", "TOP1000"),
    VocabularyWord("die Überschwemmung", "flood", "-", emptyList(), "Number: 823", "TOP1000"),
    VocabularyWord("die Dürre", "drought", "-", emptyList(), "Number: 824", "TOP1000"),
    VocabularyWord("der Sturm", "storm", "-", emptyList(), "Number: 825", "TOP1000"),
    VocabularyWord("das Unwetter", "severe weather", "-", emptyList(), "Number: 826", "TOP1000"),
    VocabularyWord("die Naturkatastrophe", "natural disaster", "-", emptyList(), "Number: 827", "TOP1000"),
    VocabularyWord("das Erdbeben", "earthquake", "-", emptyList(), "Number: 828", "TOP1000"),
    VocabularyWord("der Vulkanausbruch", "volcanic eruption", "-", emptyList(), "Number: 829", "TOP1000"),
    VocabularyWord("der Tsunami", "tsunami", "-", emptyList(), "Number: 830", "TOP1000"),
    VocabularyWord("die Epidemie", "epidemic", "-", emptyList(), "Number: 831", "TOP1000"),
    VocabularyWord("die Pandemie", "pandemic", "-", emptyList(), "Number: 832", "TOP1000"),
    VocabularyWord("die Infektion", "infection", "-", emptyList(), "Number: 833", "TOP1000"),
    VocabularyWord("das Virus", "virus", "-", emptyList(), "Number: 834", "TOP1000"),
    VocabularyWord("die Bakterien", "bacteria", "-", emptyList(), "Number: 835", "TOP1000"),
    VocabularyWord("die Impfung", "vaccination", "-", emptyList(), "Number: 836", "TOP1000"),
    VocabularyWord("die Hygiene", "hygiene", "-", emptyList(), "Number: 837", "TOP1000"),
    VocabularyWord("die Symptome", "symptoms", "-", emptyList(), "Number: 838", "TOP1000"),
    VocabularyWord("die Diagnose", "diagnosis", "-", emptyList(), "Number: 839", "TOP1000"),
    VocabularyWord("die Behandlung", "treatment", "-", emptyList(), "Number: 840", "TOP1000"),
    VocabularyWord("die Vorbeugung", "prevention", "-", emptyList(), "Number: 841", "TOP1000"),
    VocabularyWord("die Rehabilitation", "rehabilitation", "-", emptyList(), "Number: 842", "TOP1000"),
    VocabularyWord("die Pflege", "care, nursing", "-", emptyList(), "Number: 843", "TOP1000"),
    VocabularyWord("das Alter", "age, old age", "-", emptyList(), "Number: 844", "TOP1000"),
    VocabularyWord("die Jugend", "youth", "-", emptyList(), "Number: 845", "TOP1000"),
    VocabularyWord("das Erwachsenenalter", "adulthood", "-", emptyList(), "Number: 846", "TOP1000"),
    VocabularyWord("die Kindheit", "childhood", "-", emptyList(), "Number: 847", "TOP1000"),
    VocabularyWord("die Geburt", "birth", "-", emptyList(), "Number: 848", "TOP1000"),
    VocabularyWord("der Tod", "death", "-", emptyList(), "Number: 849", "TOP1000"),
    VocabularyWord("das Schicksal", "fate", "-", emptyList(), "Number: 850", "TOP1000"),
    VocabularyWord("der Zufall", "coincidence, chance", "-", emptyList(), "Number: 851", "TOP1000"),
    VocabularyWord("die Bestimmung", "destiny, determination", "-", emptyList(), "Number: 852", "TOP1000"),
    VocabularyWord("die Ethik", "ethics", "-", emptyList(), "Number: 853", "TOP1000"),
    VocabularyWord("die Moral", "morality", "-", emptyList(), "Number: 854", "TOP1000"),
    VocabularyWord("der Wert", "value", "-", emptyList(), "Number: 855", "TOP1000"),
    VocabularyWord("die Norm", "norm", "-", emptyList(), "Number: 856", "TOP1000"),
    VocabularyWord("das Prinzip", "principle", "-", emptyList(), "Number: 857", "TOP1000"),
    VocabularyWord("die Ausnahme", "exception", "-", emptyList(), "Number: 858", "TOP1000"),
    VocabularyWord("die Konsequenz", "consequence", "-", emptyList(), "Number: 859", "TOP1000"),
    VocabularyWord("der Zusammenhang", "connection", "-", emptyList(), "Number: 860", "TOP1000"),
    VocabularyWord("die Wechselwirkung", "interaction", "-", emptyList(), "Number: 861", "TOP1000"),
    VocabularyWord("das System", "system", "-", emptyList(), "Number: 862", "TOP1000"),
    VocabularyWord("die Struktur", "structure", "-", emptyList(), "Number: 863", "TOP1000"),
    VocabularyWord("der Prozess", "process", "-", emptyList(), "Number: 864", "TOP1000"),
    VocabularyWord("die Methode", "method", "-", emptyList(), "Number: 865", "TOP1000"),
    VocabularyWord("die Strategie", "strategy", "-", emptyList(), "Number: 866", "TOP1000"),
    VocabularyWord("das Konzept", "concept", "-", emptyList(), "Number: 867", "TOP1000"),
    VocabularyWord("die Theorie", "theory", "-", emptyList(), "Number: 868", "TOP1000"),
    VocabularyWord("die Praxis", "practice", "-", emptyList(), "Number: 869", "TOP1000"),
    VocabularyWord("die Studie", "study", "-", emptyList(), "Number: 870", "TOP1000"),
    VocabularyWord("die Untersuchung", "investigation", "-", emptyList(), "Number: 871", "TOP1000"),
    VocabularyWord("das Experiment", "experiment", "-", emptyList(), "Number: 872", "TOP1000"),
    VocabularyWord("die Beobachtung", "observation", "-", emptyList(), "Number: 873", "TOP1000"),
    VocabularyWord("die Messung", "measurement", "-", emptyList(), "Number: 874", "TOP1000"),
    VocabularyWord("die Daten", "data", "-", emptyList(), "Number: 875", "TOP1000"),
    VocabularyWord("die Auswertung", "evaluation", "-", emptyList(), "Number: 876", "TOP1000"),
    VocabularyWord("die Erkenntnis", "insight, finding", "-", emptyList(), "Number: 877", "TOP1000"),
    VocabularyWord("die Veröffentlichung", "publication", "-", emptyList(), "Number: 878", "TOP1000"),
    VocabularyWord("der Fachbegriff", "technical term", "-", emptyList(), "Number: 879", "TOP1000"),
    VocabularyWord("die Definition", "definition", "-", emptyList(), "Number: 880", "TOP1000"),
    VocabularyWord("die Beschreibung", "description", "-", emptyList(), "Number: 881", "TOP1000"),
    VocabularyWord("die Erklärung", "explanation", "-", emptyList(), "Number: 882", "TOP1000"),
    VocabularyWord("die Anleitung", "instruction", "-", emptyList(), "Number: 883", "TOP1000"),
    VocabularyWord("der Vergleich", "comparison", "-", emptyList(), "Number: 884", "TOP1000"),
    VocabularyWord("die Bewertung", "assessment", "-", emptyList(), "Number: 885", "TOP1000"),
    VocabularyWord("die Rezension", "review", "-", emptyList(), "Number: 886", "TOP1000"),
    VocabularyWord("die Zusammenfassung", "summary", "-", emptyList(), "Number: 887", "TOP1000"),
    VocabularyWord("das Fazit", "conclusion", "-", emptyList(), "Number: 888", "TOP1000"),
    VocabularyWord("der Ausblick", "outlook", "-", emptyList(), "Number: 889", "TOP1000"),
    VocabularyWord("die Einleitung", "introduction", "-", emptyList(), "Number: 890", "TOP1000"),
    VocabularyWord("der Hauptteil", "main part", "-", emptyList(), "Number: 891", "TOP1000"),
    VocabularyWord("das Inhaltsverzeichnis", "table of contents", "-", emptyList(), "Number: 892", "TOP1000"),
    VocabularyWord("das Literaturverzeichnis", "bibliography", "-", emptyList(), "Number: 893", "TOP1000"),
    VocabularyWord("die Fußnote", "footnote", "-", emptyList(), "Number: 894", "TOP1000"),
    VocabularyWord("die Anmerkung", "annotation, note", "-", emptyList(), "Number: 895", "TOP1000"),
    VocabularyWord("der Anhang", "appendix", "-", emptyList(), "Number: 896", "TOP1000"),
    VocabularyWord("die Abbildung", "illustration", "-", emptyList(), "Number: 897", "TOP1000"),
    VocabularyWord("das Diagramm", "diagram", "-", emptyList(), "Number: 898", "TOP1000"),
    VocabularyWord("die Kurve", "curve, graph", "-", emptyList(), "Number: 899", "TOP1000"),
    VocabularyWord("die Quelle", "source", "-", emptyList(), "Number: 900", "TOP1000"),
    VocabularyWord("das Zitat", "quote", "-", emptyList(), "Number: 901", "TOP1000"),
    VocabularyWord("die Referenz", "reference", "-", emptyList(), "Number: 902", "TOP1000"),
    VocabularyWord("der Verweis", "cross-reference", "-", emptyList(), "Number: 903", "TOP1000"),
    VocabularyWord("die Abkürzung", "abbreviation", "-", emptyList(), "Number: 904", "TOP1000"),
    VocabularyWord("das Symbol", "symbol", "-", emptyList(), "Number: 905", "TOP1000"),
    VocabularyWord("das Zeichen", "sign", "-", emptyList(), "Number: 906", "TOP1000"),
    VocabularyWord("die Bedeutung", "meaning", "-", emptyList(), "Number: 907", "TOP1000"),
    VocabularyWord("der Begriff", "term", "-", emptyList(), "Number: 908", "TOP1000"),
    VocabularyWord("die Formulierung", "formulation", "-", emptyList(), "Number: 909", "TOP1000"),
    VocabularyWord("der Ausdruck", "expression", "-", emptyList(), "Number: 910", "TOP1000"),
    VocabularyWord("das Wort", "word", "-", emptyList(), "Number: 911", "TOP1000"),
    VocabularyWord("der Satz", "sentence", "-", emptyList(), "Number: 912", "TOP1000"),
    VocabularyWord("der Absatz", "paragraph", "-", emptyList(), "Number: 913", "TOP1000"),
    VocabularyWord("das Kapitel", "chapter", "-", emptyList(), "Number: 914", "TOP1000"),
    VocabularyWord("die Passage", "passage", "-", emptyList(), "Number: 915", "TOP1000"),
    VocabularyWord("die Sprache", "language", "-", emptyList(), "Number: 916", "TOP1000"),
    VocabularyWord("die Grammatik", "grammar", "-", emptyList(), "Number: 917", "TOP1000"),
    VocabularyWord("die Rechtschreibung", "spelling", "-", emptyList(), "Number: 918", "TOP1000"),
    VocabularyWord("die Aussprache", "pronunciation", "-", emptyList(), "Number: 919", "TOP1000"),
    VocabularyWord("der Akzent", "accent", "-", emptyList(), "Number: 920", "TOP1000"),
    VocabularyWord("der Dialekt", "dialect", "-", emptyList(), "Number: 921", "TOP1000"),
    VocabularyWord("das Hochdeutsch", "Standard German", "-", emptyList(), "Number: 922", "TOP1000"),
    VocabularyWord("die Umgangssprache", "colloquial language", "-", emptyList(), "Number: 923", "TOP1000"),
    VocabularyWord("der Slang", "slang", "-", emptyList(), "Number: 924", "TOP1000"),
    VocabularyWord("die Redewendung", "idiom", "-", emptyList(), "Number: 925", "TOP1000"),
    VocabularyWord("die Übersetzung", "translation", "-", emptyList(), "Number: 926", "TOP1000"),
    VocabularyWord("das Wörterbuch", "dictionary", "-", emptyList(), "Number: 927", "TOP1000"),
    VocabularyWord("der Vokabeltrainer", "vocabulary trainer", "-", emptyList(), "Number: 928", "TOP1000"),
    VocabularyWord("die Lernmethode", "learning method", "-", emptyList(), "Number: 929", "TOP1000"),
    VocabularyWord("die Motivation", "motivation", "-", emptyList(), "Number: 930", "TOP1000"),
    VocabularyWord("die Disziplin", "discipline", "-", emptyList(), "Number: 931", "TOP1000"),
    VocabularyWord("die Routine", "routine", "-", emptyList(), "Number: 932", "TOP1000"),
    VocabularyWord("die Konzentration", "concentration", "-", emptyList(), "Number: 933", "TOP1000"),
    VocabularyWord("die Ablenkung", "distraction", "-", emptyList(), "Number: 934", "TOP1000"),
    VocabularyWord("die Zufriedenheit", "satisfaction", "-", emptyList(), "Number: 935", "TOP1000"),
    VocabularyWord("die Verantwortung", "responsibility", "-", emptyList(), "Number: 936", "TOP1000"),
    VocabularyWord("die Maßnahme", "measure", "-", emptyList(), "Number: 937", "TOP1000"),
    VocabularyWord("der Einfluss", "influence", "-", emptyList(), "Number: 938", "TOP1000"),
    VocabularyWord("die Erwartung", "expectation", "-", emptyList(), "Number: 939", "TOP1000"),
    VocabularyWord("die Voraussetzung", "prerequisite", "-", emptyList(), "Number: 940", "TOP1000"),
    VocabularyWord("das Anliegen", "concern", "-", emptyList(), "Number: 941", "TOP1000"),
    VocabularyWord("die Tragweite", "scope", "-", emptyList(), "Number: 942", "TOP1000"),
    VocabularyWord("das Bestreben", "endeavor", "-", emptyList(), "Number: 943", "TOP1000"),
    VocabularyWord("die Rücksichtnahme", "consideration", "-", emptyList(), "Number: 944", "TOP1000"),
    VocabularyWord("das Gedankengut", "ideology", "-", emptyList(), "Number: 945", "TOP1000"),
    VocabularyWord("der Sachzwang", "constraint", "-", emptyList(), "Number: 946", "TOP1000"),
    VocabularyWord("die Ambivalenz", "ambivalence", "-", emptyList(), "Number: 947", "TOP1000"),
    VocabularyWord("das Feingefühl", "sensitivity", "-", emptyList(), "Number: 948", "TOP1000"),
    VocabularyWord("die Gemütlichkeit", "coziness", "-", emptyList(), "Number: 949", "TOP1000"),
    VocabularyWord("die Sehnsucht", "longing", "-", emptyList(), "Number: 950", "TOP1000"),
    VocabularyWord("die Schadenfreude", "joy in others' misfortune", "-", emptyList(), "Number: 951", "TOP1000"),
    VocabularyWord("die Vergänglichkeit", "transience", "-", emptyList(), "Number: 952", "TOP1000"),
    VocabularyWord("das Kopfkino", "mental cinema", "-", emptyList(), "Number: 953", "TOP1000"),
    VocabularyWord("der Ohrwurm", "earworm", "-", emptyList(), "Number: 954", "TOP1000"),
    VocabularyWord("der Kummerspeck", "emotional weight gain", "-", emptyList(), "Number: 955", "TOP1000"),
    VocabularyWord("die Verschlimmbesserung", "disimprovement", "-", emptyList(), "Number: 956", "TOP1000"),
    VocabularyWord("die Hypothese", "hypothesis", "-", emptyList(), "Number: 957", "TOP1000"),
    VocabularyWord("das Paradigma", "paradigm", "-", emptyList(), "Number: 958", "TOP1000"),
    VocabularyWord("die Validität", "validity", "-", emptyList(), "Number: 959", "TOP1000"),
    VocabularyWord("die Interdisziplinarität", "interdisciplinarity", "-", emptyList(), "Number: 960", "TOP1000"),
    VocabularyWord("das Abkommen", "agreement", "-", emptyList(), "Number: 961", "TOP1000"),
    VocabularyWord("die Rechtsprechung", "jurisdiction", "-", emptyList(), "Number: 962", "TOP1000"),
    VocabularyWord("das Grundgesetz", "constitution", "-", emptyList(), "Number: 963", "TOP1000"),
    VocabularyWord("die Legislative", "legislative", "-", emptyList(), "Number: 964", "TOP1000"),
    VocabularyWord("die Exekutive", "executive", "-", emptyList(), "Number: 965", "TOP1000"),
    VocabularyWord("die Judikative", "judiciary", "-", emptyList(), "Number: 966", "TOP1000"),
    VocabularyWord("die Souveränität", "sovereignty", "-", emptyList(), "Number: 967", "TOP1000"),
    VocabularyWord("die Deflation", "deflation", "-", emptyList(), "Number: 968", "TOP1000"),
    VocabularyWord("der Leitzins", "base rate", "-", emptyList(), "Number: 969", "TOP1000"),
    VocabularyWord("die Konjunktur", "economic cycle", "-", emptyList(), "Number: 970", "TOP1000"),
    VocabularyWord("die Volatilität", "volatility", "-", emptyList(), "Number: 971", "TOP1000"),
    VocabularyWord("das Derivat", "derivative", "-", emptyList(), "Number: 972", "TOP1000"),
    VocabularyWord("die Zahlungsbilanz", "balance of payments", "-", emptyList(), "Number: 973", "TOP1000"),
    VocabularyWord("die Existenzangst", "existential anxiety", "-", emptyList(), "Number: 974", "TOP1000"),
    VocabularyWord("die kognitive Dissonanz", "cognitive dissonance", "-", emptyList(), "Number: 975", "TOP1000"),
    VocabularyWord("die Automatisierung", "automation", "-", emptyList(), "Number: 976", "TOP1000"),
    VocabularyWord("die Nanotechnologie", "nanotechnology", "-", emptyList(), "Number: 977", "TOP1000"),
    VocabularyWord("die Biotechnologie", "biotechnology", "-", emptyList(), "Number: 978", "TOP1000"),
    VocabularyWord("die Quantenphysik", "quantum physics", "-", emptyList(), "Number: 979", "TOP1000"),
    VocabularyWord("die Gentechnik", "genetic engineering", "-", emptyList(), "Number: 980", "TOP1000"),
    VocabularyWord("die Allegorie", "allegory", "-", emptyList(), "Number: 981", "TOP1000"),
    VocabularyWord("die Metapher", "metaphor", "-", emptyList(), "Number: 982", "TOP1000"),
    VocabularyWord("die Ironie", "irony", "-", emptyList(), "Number: 983", "TOP1000"),
    VocabularyWord("die Satire", "satire", "-", emptyList(), "Number: 984", "TOP1000"),
    VocabularyWord("die Eloquenz", "eloquence", "-", emptyList(), "Number: 985", "TOP1000"),
    VocabularyWord("die Prägnanz", "conciseness", "-", emptyList(), "Number: 986", "TOP1000"),
    VocabularyWord("der Tatbestand", "facts of a case", "-", emptyList(), "Number: 987", "TOP1000"),
    VocabularyWord("die Verjährung", "statute of limitations", "-", emptyList(), "Number: 988", "TOP1000"),
    VocabularyWord("die Prämisse", "premise", "-", emptyList(), "Number: 989", "TOP1000"),
    VocabularyWord("der Syllogismus", "syllogism", "-", emptyList(), "Number: 990", "TOP1000"),
    VocabularyWord("die Dialektik", "dialectics", "-", emptyList(), "Number: 991", "TOP1000"),
    VocabularyWord("der Nihilismus", "nihilism", "-", emptyList(), "Number: 992", "TOP1000"),
    VocabularyWord("die Ontologie", "ontology", "-", emptyList(), "Number: 993", "TOP1000"),
    VocabularyWord("der Solipsismus", "solipsism", "-", emptyList(), "Number: 994", "TOP1000"),
    VocabularyWord("die Reifikation", "reification", "-", emptyList(), "Number: 995", "TOP1000"),
    VocabularyWord("die Reliabilität", "reliability", "-", emptyList(), "Number: 996", "TOP1000"),
    VocabularyWord("die Stringenz", "stringency", "-", emptyList(), "Number: 997", "TOP1000"),
    VocabularyWord("die Plausibilität", "plausibility", "-", emptyList(), "Number: 998", "TOP1000"),
    VocabularyWord("die Reproduzierbarkeit", "reproducibility", "-", emptyList(), "Number: 999", "TOP1000"),
    VocabularyWord("die Evidenz", "evidence", "-", emptyList(), "Number: 1000", "TOP1000")
)
