package com.example

val a2VocabularyData = listOf(
    VocabularyWord("Vormittag", "Morning / AM", "FOR-mit-tahk", listOf(ExampleSentence("Am Vormittag habe ich Unterricht.", "// In the morning I have class.")), "Type: Noun (m) | Category: Time | IPA: /ˈfoːɐ̯mɪtaːk/", "A2"),
    VocabularyWord("Nachmittag", "Afternoon / PM", "NAKH-mit-tahk", listOf(ExampleSentence("Am Nachmittag arbeite ich.", "// In the afternoon I work.")), "Type: Noun (m) | Category: Time | IPA: /ˈnaxmɪtaːk/", "A2"),
    VocabularyWord("Viertel", "Quarter", "FEER-tel", listOf(ExampleSentence("Es ist Viertel nach drei.", "// It is quarter past three.")), "Type: Noun (n) | Category: Time | IPA: /ˈfɪʁtl̩/", "A2"),
    VocabularyWord("Halb", "Half", "halp", listOf(ExampleSentence("Es ist halb vier.", "// It is half past three. (3:30)")), "Type: Adverb | Category: Time | IPA: /halp/", "A2"),
    VocabularyWord("Sekunde", "Second", "zay-KOON-deh", listOf(ExampleSentence("Warte eine Sekunde!", "// Wait a second!")), "Type: Noun (f) | Category: Time | IPA: /zeˈkʊndə/", "A2"),
    VocabularyWord("Gestern", "Yesterday", "GES-tern", listOf(ExampleSentence("Gestern war ich im Kino.", "// Yesterday I was at the cinema.")), "Type: Adverb | Category: Time | IPA: /ˈɡɛstɐn/", "A2"),
    VocabularyWord("Morgen", "Tomorrow", "MOR-gen", listOf(ExampleSentence("Morgen gehe ich einkaufen.", "// Tomorrow I am going shopping.")), "Type: Adverb | Category: Time | IPA: /ˈmɔʁɡn̩/", "A2"),
    VocabularyWord("Dauer", "Duration", "DOW-er", listOf(ExampleSentence("Die Dauer des Kurses ist 4 Wochen.", "// The duration of the course is 4 weeks.")), "Type: Noun (f) | Category: Time | IPA: /ˈdaʊ̯ɐ/", "A2"),
    VocabularyWord("Termin", "Appointment", "tair-MEEN", listOf(ExampleSentence("Ich habe einen Termin beim Arzt.", "// I have a doctor's appointment.")), "Type: Noun (m) | Category: Time | IPA: /tɛʁˈmiːn/", "A2"),
    VocabularyWord("Frist", "Deadline", "frist", listOf(ExampleSentence("Die Frist ist nächste Woche.", "// The deadline is next week.")), "Type: Noun (f) | Category: Time | IPA: /fʁɪst/", "A2"),
    VocabularyWord("Bahnhof", "Train station", "BAHN-hohf", listOf(ExampleSentence("Wo ist der Bahnhof?", "// Where is the train station?")), "Type: Noun (m) | Category: Travel | IPA: /ˈbaːnhoːf/", "A2"),
    VocabularyWord("Flughafen", "Airport", "FLOOK-hah-fen", listOf(ExampleSentence("Wir fahren zum Flughafen.", "// We are driving to the airport.")), "Type: Noun (m) | Category: Travel | IPA: /ˈfluːkhaːfn̩/", "A2"),
    VocabularyWord("Abfahrt", "Departure", "AP-fahrt", listOf(ExampleSentence("Die Abfahrt ist um 10 Uhr.", "// The departure is at 10 o'clock.")), "Type: Noun (f) | Category: Travel | IPA: /ˈapfaːɐ̯t/", "A2"),
    VocabularyWord("Ankunft", "Arrival", "AHN-koonft", listOf(ExampleSentence("Die Ankunft verspätet sich.", "// The arrival is delayed.")), "Type: Noun (f) | Category: Travel | IPA: /ˈaŋkʊnft/", "A2"),
    VocabularyWord("Geld", "Money", "gelt", listOf(ExampleSentence("Ich habe kein Geld.", "// I have no money.")), "Type: Noun (n) | Category: Shopping | IPA: /ɡɛlt/", "A2"),
    VocabularyWord("Preis", "Price", "pryess", listOf(ExampleSentence("Der Preis ist zu hoch.", "// The price is too high.")), "Type: Noun (m) | Category: Shopping | IPA: /pʁaɪ̯s/", "A2"),
    VocabularyWord("Bezahlen", "To pay", "be-TSAH-len", listOf(ExampleSentence("Ich möchte bezahlen.", "// I would like to pay.")), "Type: Verb | Category: Shopping | IPA: /bəˈtsaːlən/", "A2"),
    VocabularyWord("Brot", "Bread", "broht", listOf(ExampleSentence("Ein Kilo Brot, bitte.", "// One kilo of bread, please.")), "Type: Noun (n) | Category: Food | IPA: /bʁoːt/", "A2"),
    VocabularyWord("Fleisch", "Meat", "flyesh", listOf(ExampleSentence("Ich esse kein Fleisch.", "// I don't eat meat.")), "Type: Noun (n) | Category: Food | IPA: /flaɪ̯ʃ/", "A2"),
    VocabularyWord("Gemüse", "Vegetables", "geh-MOO-zeh", listOf(ExampleSentence("Gemüse ist gesund.", "// Vegetables are healthy.")), "Type: Noun (n) | Category: Food | IPA: /ɡəˈmyːzə/", "A2"),
    VocabularyWord("Chef / Chefin", "Boss (m/f)", "shef / SHEF-in", listOf(ExampleSentence("Mein Chef ist streng.", "// My boss is strict.")), "Type: Noun (m/f) | Category: Work | IPA: /ʃɛf/ /ˈʃɛfɪn/", "A2"),
    VocabularyWord("Kollege", "Colleague", "ko-LAY-geh", listOf(ExampleSentence("Er ist mein Kollege.", "// He is my colleague.")), "Type: Noun (m) | Category: Work | IPA: /kɔˈlɛɡə/", "A2"),
    VocabularyWord("Meeting", "Meeting", "MEE-ting", listOf(ExampleSentence("Das Meeting beginnt um 9.", "// The meeting starts at 9.")), "Type: Noun (n) | Category: Work | IPA: /ˈmiːtɪŋ/", "A2"),
    VocabularyWord("Arzt / Ärztin", "Doctor (m/f)", "ahrtst / ERTS-tin", listOf(ExampleSentence("Ich gehe zum Arzt.", "// I am going to the doctor.")), "Type: Noun (m/f) | Category: Health | IPA: /aʁtst/ /ˈɛʁtstɪn/", "A2"),
    VocabularyWord("Krankheit", "Illness", "KRAHNK-hyte", listOf(ExampleSentence("Was ist das für eine Krankheit?", "// What kind of illness is that?")), "Type: Noun (f) | Category: Health | IPA: /ˈkʁaŋkhaɪ̯t/", "A2"),
    VocabularyWord("Schmerz", "Pain", "shmairts", listOf(ExampleSentence("Ich habe Kopfschmerzen.", "// I have a headache.")), "Type: Noun (m) | Category: Health | IPA: /ʃmɛʁts/", "A2"),
    VocabularyWord("Schule", "School", "SHOO-leh", listOf(ExampleSentence("Die Kinder sind in der Schule.", "// The children are at school.")), "Type: Noun (f) | Category: Education | IPA: /ˈʃuːlə/", "A2"),
    VocabularyWord("Prüfung", "Exam", "PROOF-oong", listOf(ExampleSentence("Die Prüfung ist schwer.", "// The exam is difficult.")), "Type: Noun (f) | Category: Education | IPA: /ˈpʁyːfʊŋ/", "A2"),
    VocabularyWord("Lernen", "To learn", "LAIR-nen", listOf(ExampleSentence("Ich lerne Deutsch.", "// I am learning German.")), "Type: Verb | Category: Education | IPA: /ˈlɛʁnən/", "A2"),
    VocabularyWord("Weil", "Because", "veyel", listOf(ExampleSentence("Ich bleibe zu Hause, weil ich krank bin.", "// I'm staying home because I am sick.")), "Type: Conjunction | Category: Grammar | IPA: /vaɪ̯l/", "A2"),
    VocabularyWord("Dass", "That", "dahs", listOf(ExampleSentence("Ich weiß, dass er kommt.", "// I know that he is coming.")), "Type: Conjunction | Category: Grammar | IPA: /das/", "A2"),
    VocabularyWord("Wenn", "If / When", "ven", listOf(ExampleSentence("Wenn es regnet, bleibe ich drinnen.", "// If it rains, I stay inside.")), "Type: Conjunction | Category: Grammar | IPA: /vɛn/", "A2"),
    VocabularyWord("Ob", "Whether", "op", listOf(ExampleSentence("Ich weiß nicht, ob er kommt.", "// I don't know whether he is coming.")), "Type: Conjunction | Category: Grammar | IPA: /ɔp/", "A2"),
    VocabularyWord("Möchten", "Would like", "MURKH-ten", listOf(ExampleSentence("Ich möchte ein Wasser, bitte.", "// I would like a water, please.")), "Type: Modal Verb | Category: Grammar | IPA: /ˈmœçtn̩/", "A2"),
    VocabularyWord("Müssen", "Must / Have to", "MOO-sen", listOf(ExampleSentence("Ich muss jetzt gehen.", "// I have to go now.")), "Type: Modal Verb | Category: Grammar | IPA: /ˈmʏsn̩/", "A2"),
    VocabularyWord("Sollen", "Should / Am supposed to", "ZOL-en", listOf(ExampleSentence("Ich soll mehr lernen.", "// I should study more.")), "Type: Modal Verb | Category: Grammar | IPA: /ˈzɔlən/", "A2"),
    VocabularyWord("War / Waren", "Was (singular/plural)", "vahr / VAH-ren", listOf(ExampleSentence("Ich war gestern müde.", "// I was tired yesterday.")), "Type: Verb | Category: Grammar | IPA: /vaːɐ̯/ /ˈvaːʁən/", "A2"),
    VocabularyWord("Hatte / Hatten", "Had", "HAH-teh / HAH-ten", listOf(ExampleSentence("Wir hatten viel Spaß.", "// We had a lot of fun.")), "Type: Verb | Category: Grammar | IPA: /ˈhatə/ /ˈhatn̩/", "A2"),
    VocabularyWord("Ich habe gestern viel gearbeitet.", "I worked a lot yesterday.", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Wir sind am Wochenende nach Berlin gefahren.", "We went to Berlin at the weekend.", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Kannst du mir beim Kochen helfen?", "Can you help me with cooking?", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Ich möchte ein Zimmer reservieren.", "I would like to reserve a room.", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Wie war dein Urlaub in Spanien?", "How was your vacation in Spain?", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Ich habe mein Handy im Bus vergessen.", "I forgot my phone on the bus.", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Wann kommst du heute nach Hause?", "When are you coming home today?", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Ich muss morgen früh aufstehen.", "I have to get up early tomorrow.", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Das hat mir sehr gut gefallen.", "I liked that very much.", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("Können wir uns morgen treffen?", "Can we meet tomorrow?", "-", emptyList(), "Category: Practice Sentences", "A2"),
    VocabularyWord("der Sitzplatz", "seat", "-", emptyList(), "Category: Travel", "A2"),
    VocabularyWord("die Jugendherberge", "youth hostel", "-", emptyList(), "Category: Travel", "A2"),
    VocabularyWord("das Einzelzimmer", "single room", "-", emptyList(), "Category: Travel", "A2"),
    VocabularyWord("der Vertrag", "contract", "-", emptyList(), "Category: Work", "A2"),
    VocabularyWord("die Besprechung", "meeting", "-", emptyList(), "Category: Work", "A2"),
    VocabularyWord("die Rechnung", "bill", "-", emptyList(), "Category: Work", "A2"),
    VocabularyWord("weil", "because", "-", emptyList(), "Category: Connectors", "A2"),
    VocabularyWord("dass", "that", "-", emptyList(), "Category: Connectors", "A2"),
    VocabularyWord("wenn", "if/when", "-", emptyList(), "Category: Connectors", "A2"),
    VocabularyWord("denken an (+ Akk)", "to think of", "-", listOf(ExampleSentence("Ich denke an dich.", "// I'm thinking of you.")), "Category: Verb Prepositions", "A2"),
    VocabularyWord("träumen von", "to dream about", "-", listOf(ExampleSentence("Ich träume von einem Urlaub.", "// I dream about a vacation.")), "Category: Verb Prepositions", "A2"),
    VocabularyWord("Passt schon.", "It's fine / That works.", "-", emptyList(), "Category: Spoken Expressions", "A2"),
    VocabularyWord("Lass uns gehen!", "Let's go!", "-", emptyList(), "Category: Spoken Expressions", "A2"),
    VocabularyWord("einen Ausflug machen", "to go on a trip", "-", emptyList(), "Category: Collocations", "A2"),
    VocabularyWord("die Prüfung bestehen", "to pass the exam", "-", emptyList(), "Category: Collocations", "A2")
)
