package com.example

val b2VocabularyData = listOf(
    VocabularyWord("Gesellschaft", "Society", "geh-ZEL-shaft", listOf(ExampleSentence("Die Gesellschaft verändert sich.", "// Society is changing.")), "Type: Noun (f) | Category: Society | IPA: /ɡəˈzɛlʃaft/", "B2"),
    VocabularyWord("Umweltschutz", "Environmental protection", "OOM-velt-shoots", listOf(ExampleSentence("Umweltschutz ist wichtig.", "// Environmental protection is important.")), "Type: Noun (m) | Category: Environment | IPA: /ˈʊmvɛltʃʊts/", "B2"),
    VocabularyWord("Nachhaltigkeit", "Sustainability", "nakh-halt-ig-kite", listOf(ExampleSentence("Nachhaltigkeit ist ein großes Thema.", "// Sustainability is a big topic.")), "Type: Noun (f) | Category: Environment | IPA: /ˈnaxhaltɪçkaɪ̯t/", "B2"),
    VocabularyWord("Investition", "Investment", "in-ves-tee-TSEE-ohn", listOf(ExampleSentence("Die Investition hat sich gelohnt.", "// The investment paid off.")), "Type: Noun (f) | Category: Business | IPA: /ɪnvɛstiˈtsi̯oːn/", "B2"),
    VocabularyWord("Umsatz", "Revenue / Turnover", "OOM-zats", listOf(ExampleSentence("Der Umsatz ist gestiegen.", "// The revenue has increased.")), "Type: Noun (m) | Category: Business | IPA: /ˈʊmzat͡s/", "B2"),
    VocabularyWord("Gewinn", "Profit", "geh-VIN", listOf(ExampleSentence("Wir haben einen hohen Gewinn erzielt.", "// We achieved a high profit.")), "Type: Noun (m) | Category: Business | IPA: /ɡəˈvɪn/", "B2"),
    VocabularyWord("Wettbewerbsfähigkeit", "Competitiveness", "VET-bair-erbs-fah-ig-kite", listOf(ExampleSentence("Die Wettbewerbsfähigkeit muss steigen.", "// Competitiveness must increase.")), "Type: Noun (f) | Category: Business | IPA: /ˈvɛtbɛːɐ̯psˌfaːɪ̯çkaɪ̯t/", "B2"),
    VocabularyWord("Freiheit", "Freedom", "FRYE-hyte", listOf(ExampleSentence("Freiheit ist ein Grundrecht.", "// Freedom is a basic right.")), "Type: Noun (f) | Category: Abstract | IPA: /ˈfʁaɪ̯haɪ̯t/", "B2"),
    VocabularyWord("Gerechtigkeit", "Justice / Fairness", "geh-REKHT-ig-kite", listOf(ExampleSentence("Wir kämpfen für Gerechtigkeit.", "// We fight for justice.")), "Type: Noun (f) | Category: Abstract | IPA: /ɡəˈʁɛçtɪçkaɪ̯t/", "B2"),
    VocabularyWord("Verantwortung", "Responsibility", "fair-ANT-vort-oong", listOf(ExampleSentence("Das ist meine Verantwortung.", "// That is my responsibility.")), "Type: Noun (f) | Category: Abstract | IPA: /fɛɐ̯ˈantvɔʁtʊŋ/", "B2"),
    VocabularyWord("Zufällig", "Random / Coincidental", "tsoo-fen-ligkh", listOf(ExampleSentence("Das war eine zufällige Begegnung.", "// That was a coincidental encounter.")), "Type: Adjective | Category: Adjectives | IPA: /tsuˈfɛnlɪç/", "B2"),
    VocabularyWord("Erheblich", "Considerable / Substantial", "air-HAYP-likh", listOf(ExampleSentence("Das ist ein erheblicher Unterschied.", "// That is a considerable difference.")), "Type: Adjective | Category: Adjectives | IPA: /ɛɐ̯ˈheːplɪç/", "B2"),
    VocabularyWord("Auffällig", "Conspicuous / Striking", "owf-fen-likh", listOf(ExampleSentence("Er trug auffällige Kleidung.", "// He wore conspicuous clothing.")), "Type: Adjective | Category: Adjectives | IPA: /ˈaʊ̯ffɛlɪç/", "B2"),
    VocabularyWord("Dennoch", "Nevertheless", "DEN-nokh", listOf(ExampleSentence("Es war kalt, dennoch gingen wir raus.", "// It was cold, nevertheless we went out.")), "Type: Adverb | Category: Grammar | IPA: /ˈdɛnɔx/", "B2"),
    VocabularyWord("Infolgedessen", "Consequently", "in-FOL-geh-des-sen", listOf(ExampleSentence("Er war krank, infolgedessen kam er nicht.", "// He was sick, consequently he didn't come.")), "Type: Adverb | Category: Grammar | IPA: /ɪnfɔlɡəˈdɛsn̩/", "B2"),
    VocabularyWord("Zwar", "Indeed / Although", "tsvahr", listOf(ExampleSentence("Es ist zwar kalt, aber die Sonne scheint.", "// It is indeed cold, but the shining is sun.")), "Type: Adverb | Category: Grammar | IPA: /tsvaːɐ̯/", "B2"),
    VocabularyWord("Bezüglich", "Regarding", "beh-TSOOG-likh", listOf(ExampleSentence("Bezüglich des Preises müssen wir reden.", "// Regarding the price, we must talk.")), "Type: Preposition | Category: Grammar | IPA: /bəˈtsuːklɪç/", "B2"),
    VocabularyWord("Hinsichtlich", "With regard to", "HIN-zikht-likh", listOf(ExampleSentence("Hinsichtlich der Qualität sind wir gut.", "// With regard to quality, we are good.")), "Type: Preposition | Category: Grammar | IPA: /ˈhɪnzɪçtlɪç/", "B2"),
    VocabularyWord("Es ist unumgänglich, dass wir uns an die neuen Regeln halten.", "It is essential that we stick to the new rules.", "-", emptyList(), "Category: Practice Sentences", "B2"),
    VocabularyWord("Unter Berücksichtigung aller Umstände war das die beste Wahl.", "Considering all circumstances, that was the best choice.", "-", emptyList(), "Category: Practice Sentences", "B2"),
    VocabularyWord("Wir müssen sicherstellen, dass das Projekt pünktlich abgeschlossen wird.", "We must ensure that the project is completed on time.", "-", emptyList(), "Category: Practice Sentences", "B2"),
    VocabularyWord("Infolgedessen mussten wir den Termin leider verschieben.", "As a result, we unfortunately had to postpone the appointment.", "-", emptyList(), "Category: Practice Sentences", "B2"),
    VocabularyWord("Ich bin fest davon überzeugt, dass wir erfolgreich sein werden.", "I am firmly convinced that we will be successful.", "-", emptyList(), "Category: Practice Sentences", "B2"),
    VocabularyWord("die Integration", "integration", "-", emptyList(), "Category: Society", "B2"),
    VocabularyWord("die Gleichberechtigung", "equality", "-", emptyList(), "Category: Society", "B2"),
    VocabularyWord("allerdings", "however", "-", emptyList(), "Category: Connectors", "B2"),
    VocabularyWord("dennoch", "nevertheless", "-", emptyList(), "Category: Connectors", "B2"),
    VocabularyWord("basieren auf (+ Dat)", "to be based on", "-", listOf(ExampleSentence("Das Buch basiert auf einer wahren Geschichte.", "// The book is based on a true story.")), "Category: Verb Prepositions", "B2"),
    VocabularyWord("Das Blaue vom Himmel versprechen", "To promise the moon", "dahs BLOW-eh fom HEM-mel fair-SPREKH-en", listOf(ExampleSentence("Politiker versprechen das Blaue vom Himmel.", "// Politicians promise the moon.")), "Type: Idiom | IPA: /das ˈblaʊ̯ə fɔm ˈhɪml̩ fɛɐ̯ˈʃpʁɛçn̩/", "B2"),
    VocabularyWord("Jemanden auf dem Kieker haben", "To have it in for someone", "YAY-man-den owf dem KEEK-er HAH-ben", listOf(ExampleSentence("Der Chef hat mich auf dem Kieker.", "// The boss has it in for me.")), "Type: Idiom | IPA: /ˈjɛːmandn̩ aʊf dɛm ˈkiːkɐ ˈhaːbn̩/", "B2")
)
